import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const en = {
  common: {
    dashboard: 'Dashboard', cooperatives: 'Cooperatives', members: 'Members', farmers: 'Farmers',
    production: 'Production', finance: 'Finance', inventory: 'Inventory', documents: 'Documents', team: 'Team',
    changePassword: 'Change password', logout: 'Log out', language: 'Language', menu: 'Menu', close: 'Close',
    loading: 'Loading…', save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', search: 'Search',
    filters: 'Filters', status: 'Status', all: 'All', from: 'From', to: 'To', date: 'Date', actions: 'Actions',
    previous: 'Previous', next: 'Next', page: 'Page', of: 'of', noResults: 'No matching records found.',
    error: 'Something went wrong. Please try again.', welcome: 'Welcome back, {{name}}',
  },
  language: { en: 'English', rw: 'Kinyarwanda', fr: 'French' },
  dashboard: {
    subtitle: "Here's what's happening across your cooperative right now.", totalMembers: 'Total members',
    activeFarmers: 'Active farmers', productionValue: 'Production value', income: 'Income', expenses: 'Expenses',
    netBalance: 'Net balance', activeLoans: 'Active loans', lowStock: 'Low stock items', needsAttention: 'Needs attention',
    allGood: 'All good', outstanding: '{{amount}} RWF outstanding', records: '{{quantity}} units across {{count}} records',
    loadError: 'Could not load dashboard data.', noCooperative: 'No cooperative is selected yet.',
  },
  reports: {
    title: 'Reports & exports', csv: 'CSV', excel: 'Excel', pdf: 'PDF', print: 'Print',
    preparing: 'Preparing report…', failed: 'Could not generate the report.', generated: 'Generated',
    generatedBy: 'Generated by', cooperative: 'Cooperative', records: 'records',
  },
  modules: {
    membersSubtitle: 'Everyone registered in your cooperative.', farmersSubtitle: 'Members with a registered farm profile.',
    financeSubtitle: 'Income, expenses, savings, and loans for your cooperative.', inventorySubtitle: 'Seeds, fertilizers, and equipment stock.',
    documentsSubtitle: 'Files attached to members, contracts, and other records.', cooperativesSubtitle: 'Every cooperative registered on the platform.',
    teamSubtitle: 'Staff and farmer user accounts for your cooperative.',
  },
  production: {
    subtitle: 'Harvest records and performance across your cooperative.', recordHarvest: 'Record harvest',
    editHarvest: 'Edit harvest record', farmer: 'Farmer', product: 'Product', quantity: 'Quantity', unit: 'Unit',
    unitPrice: 'Unit price', totalValue: 'Total value', season: 'Season', productionDate: 'Production date',
    selectFarmer: 'Select a farmer…', selectProduct: 'Select a product…', addProduct: 'Or enter a new product',
    status: 'Verification status', recorded: 'Recorded', verified: 'Verified', rejected: 'Rejected',
    noRecords: 'No production records match the selected filters.', deleteConfirm: 'Delete this production record? This cannot be undone.',
    loadError: 'Could not load production records.', saveError: 'Could not save this record. Check the details and try again.',
    totalProduction: 'Total production', activeFarmers: 'Active farmers', monthlyTrend: 'Monthly trend',
    byProduct: 'Production by product', farmerPerformance: 'Farmer performance', cooperativeComparison: 'Cooperative comparison',
  },
  auth: {
    email: 'Email address', password: 'Password', signIn: 'Sign in', forgotPassword: 'Forgot password?',
    resetPassword: 'Reset password', newPassword: 'New password', confirmPassword: 'Confirm password',
    currentPassword: 'Current password', showPassword: 'Show password', hidePassword: 'Hide password',
    passwordHint: 'Use at least 8 characters with uppercase, lowercase, and a number.',
    signInError: 'Could not sign in. Check your details and try again.', invalidCredentials: 'That email or password is incorrect.',
    signingIn: 'Signing in…', sendReset: 'Send reset link', sending: 'Sending…', backToLogin: 'Back to login',
    chooseReset: 'How would you like to reset it?', chooseResetHint: 'Choose the option that works best for you.',
    resetViaEmail: 'Reset via email', resetEmailHint: 'Get a secure reset link sent to your registered email address.',
    askAdmin: 'Ask your cooperative admin', askAdminHint: 'Your cooperative manager or SNDS admin can reset it for you directly.',
    enterEmail: "Enter your account email and we'll send you a secure reset link.", back: 'Back',
    chooseNew: 'Choose a new password', passwordReset: 'Password reset', resetSuccess: 'Your password has been updated. You can now log in.',
    goToLogin: 'Go to login', invalidResetLink: 'This reset link is invalid or incomplete. Please request a new one.',
    requestNewLink: 'Request a new link', setNewPassword: 'Set a new password', passwordsMismatch: "Passwords don't match.",
    updating: 'Updating…', updatePassword: 'Update password', done: 'Done', changed: 'Your password has been updated.',
  },
};

const rw = {
  common: {
    dashboard: 'Imbonerahamwe', cooperatives: 'Amakoperative', members: 'Abanyamuryango', farmers: 'Abahinzi',
    production: 'Umusaruro', finance: 'Imari', inventory: 'Ububiko', documents: 'Inyandiko', team: 'Abakozi',
    changePassword: 'Hindura ijambobanga', logout: 'Sohoka', language: 'Ururimi', menu: 'Ibikubiyemo', close: 'Funga',
    loading: 'Birimo gutegurwa…', save: 'Bika', cancel: 'Hagarika', edit: 'Hindura', delete: 'Siba', search: 'Shakisha',
    filters: 'Akayunguruzo', status: 'Imimerere', all: 'Byose', from: 'Kuva', to: 'Kugeza', date: 'Itariki', actions: 'Ibikorwa',
    previous: 'Ibanza', next: 'Ikurikira', page: 'Urupapuro', of: 'kuri', noResults: 'Nta makuru ahuye n’ishakisha.',
    error: 'Habaye ikibazo. Ongera ugerageze.', welcome: 'Murakaza neza, {{name}}',
  },
  language: { en: 'Icyongereza', rw: 'Kinyarwanda', fr: 'Igifaransa' },
  dashboard: {
    subtitle: 'Dore uko ibikorwa bya koperative bihagaze ubu.', totalMembers: 'Abanyamuryango bose',
    activeFarmers: 'Abahinzi bakora', productionValue: 'Agaciro k’umusaruro', income: 'Ibyinjiye', expenses: 'Ibyasohotse',
    netBalance: 'Amafaranga asigaye', activeLoans: 'Inguzanyo zikora', lowStock: 'Ibikoresho biri kugabanuka', needsAttention: 'Bikeneye kwitabwaho',
    allGood: 'Byose ni byiza', outstanding: 'Hasigaye {{amount}} RWF', records: '{{quantity}} mu nyandiko {{count}}',
    loadError: 'Ntibyashobotse kubona amakuru y’imbonerahamwe.', noCooperative: 'Nta koperative yahiswemo.',
  },
  reports: {
    title: 'Raporo no kohereza amakuru', csv: 'CSV', excel: 'Excel', pdf: 'PDF', print: 'Capisha',
    preparing: 'Raporo irimo gutegurwa…', failed: 'Raporo ntiyashoboye gukorwa.', generated: 'Yakozwe',
    generatedBy: 'Yakozwe na', cooperative: 'Koperative', records: 'inyandiko',
  },
  modules: {
    membersSubtitle: 'Abantu bose banditswe muri koperative.', farmersSubtitle: 'Abanyamuryango bafite imyirondoro y’ubuhinzi.',
    financeSubtitle: 'Ibyinjira, ibyasohotse, ubwizigame n’inguzanyo bya koperative.', inventorySubtitle: 'Imbuto, ifumbire n’ibikoresho biri mu bubiko.',
    documentsSubtitle: 'Inyandiko z’abanyamuryango, amasezerano n’izindi nyandiko.', cooperativesSubtitle: 'Amakoperative yose yanditswe kuri sisitemu.',
    teamSubtitle: 'Konti z’abakozi n’abahinzi ba koperative.',
  },
  production: {
    subtitle: 'Inyandiko z’umusaruro n’imikorere muri koperative.', recordHarvest: 'Andika umusaruro',
    editHarvest: 'Hindura inyandiko y’umusaruro', farmer: 'Umuhinzi', product: 'Igicuruzwa', quantity: 'Ingano', unit: 'Igipimo',
    unitPrice: 'Igiciro kuri kimwe', totalValue: 'Agaciro kose', season: 'Igihembwe', productionDate: 'Itariki y’umusaruro',
    selectFarmer: 'Hitamo umuhinzi…', selectProduct: 'Hitamo igicuruzwa…', addProduct: 'Cyangwa andika igicuruzwa gishya',
    status: 'Imimerere y’igenzura', recorded: 'Byanditswe', verified: 'Byemejwe', rejected: 'Byanzwe',
    noRecords: 'Nta musaruro uhuye n’akayunguruzo.', deleteConfirm: 'Siba iyi nyandiko y’umusaruro? Ntibishobora gusubizwa.',
    loadError: 'Ntibyashobotse kubona inyandiko z’umusaruro.', saveError: 'Ntibyashobotse kubika iyi nyandiko.',
    totalProduction: 'Umusaruro wose', activeFarmers: 'Abahinzi bakora', monthlyTrend: 'Imihindagurikire ya buri kwezi',
    byProduct: 'Umusaruro ku gicuruzwa', farmerPerformance: 'Imikorere y’abahinzi', cooperativeComparison: 'Igereranya ry’amakoperative',
  },
  auth: {
    email: 'Imeyili', password: 'Ijambobanga', signIn: 'Injira', forgotPassword: 'Wibagiwe ijambobanga?',
    resetPassword: 'Hindura ijambobanga', newPassword: 'Ijambobanga rishya', confirmPassword: 'Emeza ijambobanga',
    currentPassword: 'Ijambobanga risanzwe', showPassword: 'Erekana ijambobanga', hidePassword: 'Hisha ijambobanga',
    passwordHint: 'Koresha nibura inyuguti 8 zirimo inyuguti nkuru, nto n’umubare.',
    signInError: 'Kwinjira ntibyakunze. Reba amakuru wanditse wongere ugerageze.', invalidCredentials: 'Imeyili cyangwa ijambobanga si byo.',
    signingIn: 'Birimo kwinjira…', sendReset: 'Ohereza ihuza', sending: 'Birimo kohereza…', backToLogin: 'Subira aho binjirira',
    chooseReset: 'Ushaka guhindura ijambobanga ute?', chooseResetHint: 'Hitamo uburyo bukubereye.',
    resetViaEmail: 'Hindura ukoresheje imeyili', resetEmailHint: 'Oherezwa ihuza ryizewe kuri imeyili wandikishije.',
    askAdmin: 'Saba umuyobozi wa koperative', askAdminHint: 'Umuyobozi wa koperative cyangwa SNDS ashobora kuriguhindurira.',
    enterEmail: 'Andika imeyili ya konti yawe twohereze ihuza ryizewe.', back: 'Subira inyuma',
    chooseNew: 'Hitamo ijambobanga rishya', passwordReset: 'Ijambobanga ryahinduwe', resetSuccess: 'Ijambobanga ryawe ryahinduwe. Ubu ushobora kwinjira.',
    goToLogin: 'Jya kwinjira', invalidResetLink: 'Iri huza ntiryuzuye cyangwa ntirikora. Saba irindi.',
    requestNewLink: 'Saba ihuza rishya', setNewPassword: 'Shyiraho ijambobanga rishya', passwordsMismatch: 'Amagambobanga ntahura.',
    updating: 'Birimo guhindurwa…', updatePassword: 'Hindura ijambobanga', done: 'Byarangiye', changed: 'Ijambobanga ryawe ryahinduwe.',
  },
};

const fr = {
  common: {
    dashboard: 'Tableau de bord', cooperatives: 'Coopératives', members: 'Membres', farmers: 'Agriculteurs',
    production: 'Production', finance: 'Finances', inventory: 'Inventaire', documents: 'Documents', team: 'Équipe',
    changePassword: 'Changer le mot de passe', logout: 'Déconnexion', language: 'Langue', menu: 'Menu', close: 'Fermer',
    loading: 'Chargement…', save: 'Enregistrer', cancel: 'Annuler', edit: 'Modifier', delete: 'Supprimer', search: 'Rechercher',
    filters: 'Filtres', status: 'Statut', all: 'Tous', from: 'Du', to: 'Au', date: 'Date', actions: 'Actions',
    previous: 'Précédent', next: 'Suivant', page: 'Page', of: 'sur', noResults: 'Aucun enregistrement correspondant.',
    error: 'Une erreur est survenue. Réessayez.', welcome: 'Bienvenue, {{name}}',
  },
  language: { en: 'Anglais', rw: 'Kinyarwanda', fr: 'Français' },
  dashboard: {
    subtitle: 'Voici la situation actuelle de votre coopérative.', totalMembers: 'Total des membres',
    activeFarmers: 'Agriculteurs actifs', productionValue: 'Valeur de production', income: 'Revenus', expenses: 'Dépenses',
    netBalance: 'Solde net', activeLoans: 'Prêts actifs', lowStock: 'Articles en stock faible', needsAttention: 'Attention requise',
    allGood: 'Tout va bien', outstanding: '{{amount}} RWF restant', records: '{{quantity}} unités dans {{count}} enregistrements',
    loadError: 'Impossible de charger le tableau de bord.', noCooperative: 'Aucune coopérative sélectionnée.',
  },
  reports: {
    title: 'Rapports et exportations', csv: 'CSV', excel: 'Excel', pdf: 'PDF', print: 'Imprimer',
    preparing: 'Préparation du rapport…', failed: 'Impossible de générer le rapport.', generated: 'Généré',
    generatedBy: 'Généré par', cooperative: 'Coopérative', records: 'enregistrements',
  },
  modules: {
    membersSubtitle: 'Toutes les personnes inscrites dans votre coopérative.', farmersSubtitle: 'Membres ayant un profil agricole.',
    financeSubtitle: 'Revenus, dépenses, épargne et prêts de votre coopérative.', inventorySubtitle: 'Stocks de semences, engrais et équipements.',
    documentsSubtitle: 'Fichiers des membres, contrats et autres dossiers.', cooperativesSubtitle: 'Toutes les coopératives inscrites sur la plateforme.',
    teamSubtitle: 'Comptes du personnel et des agriculteurs de votre coopérative.',
  },
  production: {
    subtitle: 'Récoltes et performances de votre coopérative.', recordHarvest: 'Enregistrer une récolte',
    editHarvest: 'Modifier la récolte', farmer: 'Agriculteur', product: 'Produit', quantity: 'Quantité', unit: 'Unité',
    unitPrice: 'Prix unitaire', totalValue: 'Valeur totale', season: 'Saison', productionDate: 'Date de production',
    selectFarmer: 'Sélectionner un agriculteur…', selectProduct: 'Sélectionner un produit…', addProduct: 'Ou saisir un nouveau produit',
    status: 'Statut de vérification', recorded: 'Enregistré', verified: 'Vérifié', rejected: 'Rejeté',
    noRecords: 'Aucune production ne correspond aux filtres.', deleteConfirm: 'Supprimer cette production ? Cette action est irréversible.',
    loadError: 'Impossible de charger les productions.', saveError: 'Impossible d’enregistrer. Vérifiez les données.',
    totalProduction: 'Production totale', activeFarmers: 'Agriculteurs actifs', monthlyTrend: 'Tendance mensuelle',
    byProduct: 'Production par produit', farmerPerformance: 'Performance des agriculteurs', cooperativeComparison: 'Comparaison des coopératives',
  },
  auth: {
    email: 'Adresse e-mail', password: 'Mot de passe', signIn: 'Se connecter', forgotPassword: 'Mot de passe oublié ?',
    resetPassword: 'Réinitialiser le mot de passe', newPassword: 'Nouveau mot de passe', confirmPassword: 'Confirmer le mot de passe',
    currentPassword: 'Mot de passe actuel', showPassword: 'Afficher le mot de passe', hidePassword: 'Masquer le mot de passe',
    passwordHint: 'Utilisez au moins 8 caractères avec majuscule, minuscule et chiffre.',
    signInError: 'Connexion impossible. Vérifiez vos informations et réessayez.', invalidCredentials: 'Adresse e-mail ou mot de passe incorrect.',
    signingIn: 'Connexion…', sendReset: 'Envoyer le lien', sending: 'Envoi…', backToLogin: 'Retour à la connexion',
    chooseReset: 'Comment souhaitez-vous le réinitialiser ?', chooseResetHint: 'Choisissez l’option qui vous convient.',
    resetViaEmail: 'Réinitialiser par e-mail', resetEmailHint: 'Recevez un lien sécurisé à votre adresse enregistrée.',
    askAdmin: 'Demander à votre administrateur', askAdminHint: 'Le gestionnaire ou l’administrateur SNDS peut le réinitialiser.',
    enterEmail: 'Saisissez votre e-mail et nous vous enverrons un lien sécurisé.', back: 'Retour',
    chooseNew: 'Choisissez un nouveau mot de passe', passwordReset: 'Mot de passe réinitialisé', resetSuccess: 'Votre mot de passe a été mis à jour. Vous pouvez vous connecter.',
    goToLogin: 'Aller à la connexion', invalidResetLink: 'Ce lien est invalide ou incomplet. Demandez-en un nouveau.',
    requestNewLink: 'Demander un nouveau lien', setNewPassword: 'Définir un nouveau mot de passe', passwordsMismatch: 'Les mots de passe ne correspondent pas.',
    updating: 'Mise à jour…', updatePassword: 'Mettre à jour', done: 'Terminé', changed: 'Votre mot de passe a été mis à jour.',
  },
};

en.documents = {
  upload: 'Upload document', uploading: 'Uploading...', file: 'File', member: 'Member', description: 'Description', size: 'Size',
  selectMember: 'Select a member...', chooseFile: 'Choose a file to upload.', optional: 'optional',
  fileTypes: 'PDF, JPG, PNG, WEBP, Word, Excel, or TXT - max 10MB.', example: 'e.g. National ID copy',
  loadError: 'Could not load documents.', empty: 'No documents uploaded yet.', uploadError: 'Could not upload this file.',
  deleteConfirm: 'Delete "{{name}}"? This cannot be undone.', deleteError: 'Could not delete this document.', download: 'Download',
};

rw.documents = {
  upload: 'Ohereza inyandiko', uploading: 'Birimo koherezwa...', file: 'Dosiye', member: 'Umunyamuryango', description: 'Ibisobanuro', size: 'Ingano',
  selectMember: 'Hitamo umunyamuryango...', chooseFile: 'Hitamo dosiye yo kohereza.', optional: 'si ngombwa',
  fileTypes: 'PDF, JPG, PNG, WEBP, Word, Excel cyangwa TXT - ntirenze 10MB.', example: 'urugero: Kopi y\'indangamuntu',
  loadError: 'Ntibyashobotse kubona inyandiko.', empty: 'Nta nyandiko irashyirwaho.', uploadError: 'Iyi dosiye ntiyashoboye koherezwa.',
  deleteConfirm: 'Siba "{{name}}"? Ntibishobora gusubizwa.', deleteError: 'Inyandiko ntiyashoboye gusibwa.', download: 'Kuramo',
};

fr.documents = {
  upload: 'Televerser un document', uploading: 'Televersement...', file: 'Fichier', member: 'Membre', description: 'Description', size: 'Taille',
  selectMember: 'Selectionner un membre...', chooseFile: 'Choisissez un fichier a televerser.', optional: 'facultatif',
  fileTypes: 'PDF, JPG, PNG, WEBP, Word, Excel ou TXT - 10 Mo maximum.', example: 'p. ex. copie de la carte d\'identite',
  loadError: 'Impossible de charger les documents.', empty: 'Aucun document televerse.', uploadError: 'Impossible de televerser ce fichier.',
  deleteConfirm: 'Supprimer "{{name}}" ? Cette action est irreversible.', deleteError: 'Impossible de supprimer ce document.', download: 'Telecharger',
};

const savedLanguage = localStorage.getItem('scfmp_language') || 'en';

i18n.use(initReactI18next).init({
  resources: { en: { translation: en }, rw: { translation: rw }, fr: { translation: fr } },
  lng: ['en', 'rw', 'fr'].includes(savedLanguage) ? savedLanguage : 'en',
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
});

document.documentElement.lang = i18n.language;
i18n.on('languageChanged', (language) => {
  localStorage.setItem('scfmp_language', language);
  document.documentElement.lang = language;
});

export default i18n;
