import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const en = {
  common: {
    dashboard: 'Dashboard', cooperatives: 'Cooperatives', members: 'Members', farmers: 'Farmers',
    production: 'Production', finance: 'Finance', inventory: 'Inventory', documents: 'Documents', team: 'Team',
    changePassword: 'Change password', logout: 'Log out', language: 'Language', menu: 'Menu', close: 'Close',
    loading: 'Loading…', save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', search: 'Search',
    filters: 'Filters', status: 'Status', all: 'All', from: 'From', to: 'To', date: 'Date', actions: 'Actions',
    previous: 'Previous', next: 'Next', page: 'Page', of: 'of', noResults: 'No matching records found.',
    error: 'Something went wrong. Please try again.', welcome: 'Welcome back, {{name}}',
  },
  language: { en: 'English', rw: 'Kinyarwanda', fr: 'French' },
  dashboard: {
    subtitle: "Here's what's happening across your cooperative right now.", totalMembers: 'Total members',
    activeFarmers: 'Active farmers', productionValue: 'Production value', income: 'Income', expenses: 'Expenses',
    netBalance: 'Net balance', activeLoans: 'Active loans', lowStock: 'Low stock items', needsAttention: 'Needs attention',
    allGood: 'All good', outstanding: '{{amount}} RWF outstanding', records: '{{quantity}} units across {{count}} records',
    loadError: 'Could not load dashboard data.', noCooperative: 'No cooperative is selected yet.',
  },
  reports: {
    title: 'Reports & exports', csv: 'CSV', excel: 'Excel', pdf: 'PDF', print: 'Print',
    preparing: 'Preparing report…', failed: 'Could not generate the report.', generated: 'Generated',
    generatedBy: 'Generated by', cooperative: 'Organization', records: 'records',
  },
  modules: {
    membersSubtitle: 'Everyone registered in your cooperative.', farmersSubtitle: 'Members with a registered farm profile.',
    financeSubtitle: 'Income, expenses, savings, and loans for your cooperative.', inventorySubtitle: 'Seeds, fertilizers, and equipment stock.',
    documentsSubtitle: 'Files attached to members, contracts, and other records.', cooperativesSubtitle: 'Every cooperative registered on the platform.',
    teamSubtitle: 'Staff and farmer user accounts for your cooperative.',
  },
  production: {
    subtitle: 'Harvest records and performance across your cooperative.', recordHarvest: 'Record harvest',
    editHarvest: 'Edit harvest record', farmer: 'Farmer', product: 'Product', quantity: 'Quantity', unit: 'Unit',
    unitPrice: 'Unit price', totalValue: 'Total value', season: 'Season', productionDate: 'Production date',
    selectFarmer: 'Select a farmer…', selectProduct: 'Select a product…', addProduct: 'Or enter a new product',
    status: 'Verification status', recorded: 'Recorded', verified: 'Verified', rejected: 'Rejected',
    noRecords: 'No production records match the selected filters.', deleteConfirm: 'Delete this production record? This cannot be undone.',
    loadError: 'Could not load production records.', saveError: 'Could not save this record. Check the details and try again.',
    totalProduction: 'Total production', activeFarmers: 'Active farmers', monthlyTrend: 'Monthly trend',
    byProduct: 'Production by product', farmerPerformance: 'Farmer performance', cooperativeComparison: 'Organization comparison',
  },
  auth: {
    email: 'Email address', password: 'Password', signIn: 'Sign in', forgotPassword: 'Forgot password?',
    resetPassword: 'Reset password', newPassword: 'New password', confirmPassword: 'Confirm password',
    currentPassword: 'Current password', showPassword: 'Show password', hidePassword: 'Hide password',
    passwordHint: 'Use at least 8 characters with uppercase, lowercase, and a number.',
    signInError: 'Could not sign in. Check your details and try again.', invalidCredentials: 'That email or password is incorrect.',
    signingIn: 'Signing in…', sendReset: 'Send reset link', sending: 'Sending…', backToLogin: 'Back to login',
    chooseReset: 'How would you like to reset it?', chooseResetHint: 'Choose the option that works best for you.',
    resetViaEmail: 'Reset via email', resetEmailHint: 'Get a secure reset link sent to your registered email address.',
    askAdmin: 'Ask your organization admin', askAdminHint: 'Your organization manager or SmartBridge Technologies Ltd administrator can reset it for you directly.',
    enterEmail: "Enter your account email and we'll send you a secure reset link.", back: 'Back',
    chooseNew: 'Choose a new password', passwordReset: 'Password reset', resetSuccess: 'Your password has been updated. You can now log in.',
    goToLogin: 'Go to login', invalidResetLink: 'This reset link is invalid or incomplete. Please request a new one.',
    requestNewLink: 'Request a new link', setNewPassword: 'Set a new password', passwordsMismatch: "Passwords don't match.",
    updating: 'Updating…', updatePassword: 'Update password', done: 'Done', changed: 'Your password has been updated.',
  },
};

const rw = {
  common: {
    dashboard: 'Imbonerahamwe', cooperatives: 'Amakoperative', members: 'Abanyamuryango', farmers: 'Abahinzi',
    production: 'Umusaruro', finance: 'Imari', inventory: 'Ububiko', documents: 'Inyandiko', team: 'Abakozi',
    changePassword: 'Hindura ijambobanga', logout: 'Sohoka', language: 'Ururimi', menu: 'Ibikubiyemo', close: 'Funga',
    loading: 'Birimo gutegurwa…', save: 'Bika', cancel: 'Hagarika', edit: 'Hindura', delete: 'Siba', search: 'Shakisha',
    filters: 'Akayunguruzo', status: 'Imimerere', all: 'Byose', from: 'Kuva', to: 'Kugeza', date: 'Itariki', actions: 'Ibikorwa',
    previous: 'Ibanza', next: 'Ikurikira', page: 'Urupapuro', of: 'kuri', noResults: 'Nta makuru ahuye n’ishakisha.',
    error: 'Habaye ikibazo. Ongera ugerageze.', welcome: 'Murakaza neza, {{name}}',
  },
  language: { en: 'Icyongereza', rw: 'Kinyarwanda', fr: 'Igifaransa' },
  dashboard: {
    subtitle: 'Dore uko ibikorwa bya koperative bihagaze ubu.', totalMembers: 'Abanyamuryango bose',
    activeFarmers: 'Abahinzi bakora', productionValue: 'Agaciro k’umusaruro', income: 'Ibyinjiye', expenses: 'Ibyasohotse',
    netBalance: 'Amafaranga asigaye', activeLoans: 'Inguzanyo zikora', lowStock: 'Ibikoresho biri kugabanuka', needsAttention: 'Bikeneye kwitabwaho',
    allGood: 'Byose ni byiza', outstanding: 'Hasigaye {{amount}} RWF', records: '{{quantity}} mu nyandiko {{count}}',
    loadError: 'Ntibyashobotse kubona amakuru y’imbonerahamwe.', noCooperative: 'Nta koperative yahiswemo.',
  },
  reports: {
    title: 'Raporo no kohereza amakuru', csv: 'CSV', excel: 'Excel', pdf: 'PDF', print: 'Capisha',
    preparing: 'Raporo irimo gutegurwa…', failed: 'Raporo ntiyashoboye gukorwa.', generated: 'Yakozwe',
    generatedBy: 'Yakozwe na', cooperative: 'Umuryango', records: 'inyandiko',
  },
  modules: {
    membersSubtitle: 'Abantu bose banditswe muri koperative.', farmersSubtitle: 'Abanyamuryango bafite imyirondoro y’ubuhinzi.',
    financeSubtitle: 'Ibyinjira, ibyasohotse, ubwizigame n’inguzanyo bya koperative.', inventorySubtitle: 'Imbuto, ifumbire n’ibikoresho biri mu bubiko.',
    documentsSubtitle: 'Inyandiko z’abanyamuryango, amasezerano n’izindi nyandiko.', cooperativesSubtitle: 'Amakoperative yose yanditswe kuri sisitemu.',
    teamSubtitle: 'Konti z’abakozi n’abahinzi ba koperative.',
  },
  production: {
    subtitle: 'Inyandiko z’umusaruro n’imikorere muri koperative.', recordHarvest: 'Andika umusaruro',
    editHarvest: 'Hindura inyandiko y’umusaruro', farmer: 'Umuhinzi', product: 'Igicuruzwa', quantity: 'Ingano', unit: 'Igipimo',
    unitPrice: 'Igiciro kuri kimwe', totalValue: 'Agaciro kose', season: 'Igihembwe', productionDate: 'Itariki y’umusaruro',
    selectFarmer: 'Hitamo umuhinzi…', selectProduct: 'Hitamo igicuruzwa…', addProduct: 'Cyangwa andika igicuruzwa gishya',
    status: 'Imimerere y’igenzura', recorded: 'Byanditswe', verified: 'Byemejwe', rejected: 'Byanzwe',
    noRecords: 'Nta musaruro uhuye n’akayunguruzo.', deleteConfirm: 'Siba iyi nyandiko y’umusaruro? Ntibishobora gusubizwa.',
    loadError: 'Ntibyashobotse kubona inyandiko z’umusaruro.', saveError: 'Ntibyashobotse kubika iyi nyandiko.',
    totalProduction: 'Umusaruro wose', activeFarmers: 'Abahinzi bakora', monthlyTrend: 'Imihindagurikire ya buri kwezi',
    byProduct: 'Umusaruro ku gicuruzwa', farmerPerformance: 'Imikorere y’abahinzi', cooperativeComparison: 'Igereranya ry’imiryango',
  },
  auth: {
    email: 'Imeyili', password: 'Ijambobanga', signIn: 'Injira', forgotPassword: 'Wibagiwe ijambobanga?',
    resetPassword: 'Hindura ijambobanga', newPassword: 'Ijambobanga rishya', confirmPassword: 'Emeza ijambobanga',
    currentPassword: 'Ijambobanga risanzwe', showPassword: 'Erekana ijambobanga', hidePassword: 'Hisha ijambobanga',
    passwordHint: 'Koresha nibura inyuguti 8 zirimo inyuguti nkuru, nto n’umubare.',
    signInError: 'Kwinjira ntibyakunze. Reba amakuru wanditse wongere ugerageze.', invalidCredentials: 'Imeyili cyangwa ijambobanga si byo.',
    signingIn: 'Birimo kwinjira…', sendReset: 'Ohereza ihuza', sending: 'Birimo kohereza…', backToLogin: 'Subira aho binjirira',
    chooseReset: 'Ushaka guhindura ijambobanga ute?', chooseResetHint: 'Hitamo uburyo bukubereye.',
    resetViaEmail: 'Hindura ukoresheje imeyili', resetEmailHint: 'Oherezwa ihuza ryizewe kuri imeyili wandikishije.',
    askAdmin: 'Saba umuyobozi w’umuryango', askAdminHint: 'Umuyobozi w’umuryango cyangwa umuyobozi wa SmartBridge Technologies Ltd ashobora kuriguhindurira.',
    enterEmail: 'Andika imeyili ya konti yawe twohereze ihuza ryizewe.', back: 'Subira inyuma',
    chooseNew: 'Hitamo ijambobanga rishya', passwordReset: 'Ijambobanga ryahinduwe', resetSuccess: 'Ijambobanga ryawe ryahinduwe. Ubu ushobora kwinjira.',
    goToLogin: 'Jya kwinjira', invalidResetLink: 'Iri huza ntiryuzuye cyangwa ntirikora. Saba irindi.',
    requestNewLink: 'Saba ihuza rishya', setNewPassword: 'Shyiraho ijambobanga rishya', passwordsMismatch: 'Amagambobanga ntahura.',
    updating: 'Birimo guhindurwa…', updatePassword: 'Hindura ijambobanga', done: 'Byarangiye', changed: 'Ijambobanga ryawe ryahinduwe.',
  },
};

const fr = {
  common: {
    dashboard: 'Tableau de bord', cooperatives: 'Coopératives', members: 'Membres', farmers: 'Agriculteurs',
    production: 'Production', finance: 'Finances', inventory: 'Inventaire', documents: 'Documents', team: 'Équipe',
    changePassword: 'Changer le mot de passe', logout: 'Déconnexion', language: 'Langue', menu: 'Menu', close: 'Fermer',
    loading: 'Chargement…', save: 'Enregistrer', cancel: 'Annuler', edit: 'Modifier', delete: 'Supprimer', search: 'Rechercher',
    filters: 'Filtres', status: 'Statut', all: 'Tous', from: 'Du', to: 'Au', date: 'Date', actions: 'Actions',
    previous: 'Précédent', next: 'Suivant', page: 'Page', of: 'sur', noResults: 'Aucun enregistrement correspondant.',
    error: 'Une erreur est survenue. Réessayez.', welcome: 'Bienvenue, {{name}}',
  },
  language: { en: 'Anglais', rw: 'Kinyarwanda', fr: 'Français' },
  dashboard: {
    subtitle: 'Voici la situation actuelle de votre coopérative.', totalMembers: 'Total des membres',
    activeFarmers: 'Agriculteurs actifs', productionValue: 'Valeur de production', income: 'Revenus', expenses: 'Dépenses',
    netBalance: 'Solde net', activeLoans: 'Prêts actifs', lowStock: 'Articles en stock faible', needsAttention: 'Attention requise',
    allGood: 'Tout va bien', outstanding: '{{amount}} RWF restant', records: '{{quantity}} unités dans {{count}} enregistrements',
    loadError: 'Impossible de charger le tableau de bord.', noCooperative: 'Aucune coopérative sélectionnée.',
  },
  reports: {
    title: 'Rapports et exportations', csv: 'CSV', excel: 'Excel', pdf: 'PDF', print: 'Imprimer',
    preparing: 'Préparation du rapport…', failed: 'Impossible de générer le rapport.', generated: 'Généré',
    generatedBy: 'Généré par', cooperative: 'Organisation', records: 'enregistrements',
  },
  modules: {
    membersSubtitle: 'Toutes les personnes inscrites dans votre coopérative.', farmersSubtitle: 'Membres ayant un profil agricole.',
    financeSubtitle: 'Revenus, dépenses, épargne et prêts de votre coopérative.', inventorySubtitle: 'Stocks de semences, engrais et équipements.',
    documentsSubtitle: 'Fichiers des membres, contrats et autres dossiers.', cooperativesSubtitle: 'Toutes les coopératives inscrites sur la plateforme.',
    teamSubtitle: 'Comptes du personnel et des agriculteurs de votre coopérative.',
  },
  production: {
    subtitle: 'Récoltes et performances de votre coopérative.', recordHarvest: 'Enregistrer une récolte',
    editHarvest: 'Modifier la récolte', farmer: 'Agriculteur', product: 'Produit', quantity: 'Quantité', unit: 'Unité',
    unitPrice: 'Prix unitaire', totalValue: 'Valeur totale', season: 'Saison', productionDate: 'Date de production',
    selectFarmer: 'Sélectionner un agriculteur…', selectProduct: 'Sélectionner un produit…', addProduct: 'Ou saisir un nouveau produit',
    status: 'Statut de vérification', recorded: 'Enregistré', verified: 'Vérifié', rejected: 'Rejeté',
    noRecords: 'Aucune production ne correspond aux filtres.', deleteConfirm: 'Supprimer cette production ? Cette action est irréversible.',
    loadError: 'Impossible de charger les productions.', saveError: 'Impossible d’enregistrer. Vérifiez les données.',
    totalProduction: 'Production totale', activeFarmers: 'Agriculteurs actifs', monthlyTrend: 'Tendance mensuelle',
    byProduct: 'Production par produit', farmerPerformance: 'Performance des agriculteurs', cooperativeComparison: 'Comparaison des organisations',
  },
  auth: {
    email: 'Adresse e-mail', password: 'Mot de passe', signIn: 'Se connecter', forgotPassword: 'Mot de passe oublié ?',
    resetPassword: 'Réinitialiser le mot de passe', newPassword: 'Nouveau mot de passe', confirmPassword: 'Confirmer le mot de passe',
    currentPassword: 'Mot de passe actuel', showPassword: 'Afficher le mot de passe', hidePassword: 'Masquer le mot de passe',
    passwordHint: 'Utilisez au moins 8 caractères avec majuscule, minuscule et chiffre.',
    signInError: 'Connexion impossible. Vérifiez vos informations et réessayez.', invalidCredentials: 'Adresse e-mail ou mot de passe incorrect.',
    signingIn: 'Connexion…', sendReset: 'Envoyer le lien', sending: 'Envoi…', backToLogin: 'Retour à la connexion',
    chooseReset: 'Comment souhaitez-vous le réinitialiser ?', chooseResetHint: 'Choisissez l’option qui vous convient.',
    resetViaEmail: 'Réinitialiser par e-mail', resetEmailHint: 'Recevez un lien sécurisé à votre adresse enregistrée.',
    askAdmin: 'Demander à l’administrateur de votre organisation', askAdminHint: 'Le gestionnaire de votre organisation ou un administrateur de SmartBridge Technologies Ltd peut le réinitialiser.',
    enterEmail: 'Saisissez votre e-mail et nous vous enverrons un lien sécurisé.', back: 'Retour',
    chooseNew: 'Choisissez un nouveau mot de passe', passwordReset: 'Mot de passe réinitialisé', resetSuccess: 'Votre mot de passe a été mis à jour. Vous pouvez vous connecter.',
    goToLogin: 'Aller à la connexion', invalidResetLink: 'Ce lien est invalide ou incomplet. Demandez-en un nouveau.',
    requestNewLink: 'Demander un nouveau lien', setNewPassword: 'Définir un nouveau mot de passe', passwordsMismatch: 'Les mots de passe ne correspondent pas.',
    updating: 'Mise à jour…', updatePassword: 'Mettre à jour', done: 'Terminé', changed: 'Votre mot de passe a été mis à jour.',
  },
};

en.documents = {
  upload: 'Upload document', uploading: 'Uploading...', file: 'File', member: 'Member', description: 'Description', size: 'Size',
  selectMember: 'Select a member...', chooseFile: 'Choose a file to upload.', optional: 'optional',
  fileTypes: 'PDF, JPG, PNG, WEBP, Word, Excel, or TXT - max 4 MB.', example: 'e.g. National ID copy',
  loadError: 'Could not load documents.', empty: 'No documents uploaded yet.', uploadError: 'Could not upload this file.',
  uploaded: 'Document uploaded successfully.', fileTooLarge: 'Choose a file no larger than 4 MB.',
  fileTypeUnsupported: 'Choose a supported PDF, image, Word, Excel, or TXT file.', fileNameTooLong: 'The file name is too long.',
  storageUnavailable: 'Document storage is unavailable. Ask the system administrator to connect Vercel Blob.',
  storageUploadFailed: 'The file could not be stored. Please try again.',
  deleteConfirm: 'Delete "{{name}}"? This cannot be undone.', deleteError: 'Could not delete this document.', download: 'Download',
};

rw.documents = {
  upload: 'Ohereza inyandiko', uploading: 'Birimo koherezwa...', file: 'Dosiye', member: 'Umunyamuryango', description: 'Ibisobanuro', size: 'Ingano',
  selectMember: 'Hitamo umunyamuryango...', chooseFile: 'Hitamo dosiye yo kohereza.', optional: 'si ngombwa',
  fileTypes: 'PDF, JPG, PNG, WEBP, Word, Excel cyangwa TXT - ntirenze 4 MB.', example: 'urugero: Kopi y\'indangamuntu',
  loadError: 'Ntibyashobotse kubona inyandiko.', empty: 'Nta nyandiko irashyirwaho.', uploadError: 'Iyi dosiye ntiyashoboye koherezwa.',
  uploaded: 'Inyandiko yoherejwe neza.', fileTooLarge: 'Hitamo dosiye itarengeje 4 MB.',
  fileTypeUnsupported: 'Hitamo dosiye ya PDF, ifoto, Word, Excel cyangwa TXT yemewe.', fileNameTooLong: 'Izina rya dosiye ni rirerire cyane.',
  storageUnavailable: 'Ububiko bw\'inyandiko ntiburi gukora ubu. Bwira umuyobozi wa sisitemu ahuze Vercel Blob.',
  storageUploadFailed: 'Dosiye ntiyashoboye kubikwa. Ongera ugerageze.',
  deleteConfirm: 'Siba "{{name}}"? Ntibishobora gusubizwa.', deleteError: 'Inyandiko ntiyashoboye gusibwa.', download: 'Kuramo',
};

fr.documents = {
  upload: 'Televerser un document', uploading: 'Televersement...', file: 'Fichier', member: 'Membre', description: 'Description', size: 'Taille',
  selectMember: 'Selectionner un membre...', chooseFile: 'Choisissez un fichier a televerser.', optional: 'facultatif',
  fileTypes: 'PDF, JPG, PNG, WEBP, Word, Excel ou TXT - 4 Mo maximum.', example: 'p. ex. copie de la carte d\'identite',
  loadError: 'Impossible de charger les documents.', empty: 'Aucun document televerse.', uploadError: 'Impossible de televerser ce fichier.',
  uploaded: 'Document téléversé avec succès.', fileTooLarge: 'Choisissez un fichier de 4 Mo maximum.',
  fileTypeUnsupported: 'Choisissez un fichier PDF, image, Word, Excel ou TXT pris en charge.', fileNameTooLong: 'Le nom du fichier est trop long.',
  storageUnavailable: 'Le stockage des documents est indisponible. Demandez à l’administrateur de connecter Vercel Blob.',
  storageUploadFailed: 'Le fichier n’a pas pu être stocké. Réessayez.',
  deleteConfirm: 'Supprimer "{{name}}" ? Cette action est irreversible.', deleteError: 'Impossible de supprimer ce document.', download: 'Telecharger',
};

Object.assign(en.common, {
  cooperatives: 'Organizations', organizations: 'Organizations', contact: 'Contact', view: 'View',
  optional: 'Optional', saving: 'Saving...', farmer: 'Farmer',
});
Object.assign(en.dashboard, {
  subtitle: "Here's what's happening across your organization right now.",
  noCooperative: 'No organization is selected yet.',
  organizationWelcome: 'Welcome to {{organization}}',
});
Object.assign(en.modules, {
  membersSubtitle: 'Everyone registered in your organization.',
  farmersSubtitle: 'Members with a registered farm profile.',
  financeSubtitle: 'Income, expenses, savings, and loans for your organization.',
  cooperativesSubtitle: 'Manage all organizations registered on the platform.',
  teamSubtitle: 'Staff and farmer user accounts for your organization.',
});
Object.assign(en.auth, {
  askAdmin: 'Ask your organization admin',
  askAdminHint: 'Your organization manager or SmartBridge Technologies Ltd administrator can reset it for you directly.',
  adminResetInstructions: 'Contact your organization manager or SmartBridge Technologies Ltd super admin. From Staff Accounts, they can reset your password and share a new temporary one with you directly.',
});
Object.assign(en.production, {
  productionMode: 'Production mode', individual: 'Individual', group: 'Group', producer: 'Producer',
  farmerGroup: 'Farmer group', selectFarmerGroup: 'Select a farmer group…',
  productionGroup: 'Production group', selectProductionGroup: 'Select a production group…',
  selectOrganization: 'Select an organization before adding production.',
  cropType: 'Crop type', selectCropType: 'Select a crop type…', addCropType: 'Or enter a new crop type',
  expectedProduction: 'Expected production', actualHarvest: 'Actual harvest', harvestDate: 'Harvest date',
  productionLocation: 'Farm / production location', notes: 'Notes', activeProducers: 'Active producers',
  subtitle: 'Harvest records and performance across your organization.',
  cooperativeComparison: 'Organization comparison',
});
en.reports.cooperative = 'Organization';
en.organizations = {
  subtitle: 'Manage all organizations registered on the platform.', add: 'Add Organization',
  edit: 'Edit Organization', details: 'Organization details', create: 'Create Organization',
  saveChanges: 'Save changes', loading: 'Loading organizations...', empty: 'No organizations yet — add your first one to get started.',
  noneShort: 'No organizations yet', select: 'Select organization', switch: 'Switch to this organization',
  current: 'Currently viewing', created: 'Organization created successfully.', updated: 'Organization updated successfully.',
  deleted: 'Organization deleted successfully.', saveError: 'Could not save this organization. Check the details and try again.',
  deleteConfirm: 'Delete {{name}}? This is allowed only when the organization has no related records.',
  deleteBlocked: 'This organization cannot be deleted because it has members, users, financial, production, inventory, document, or audit records.',
  deleteError: 'Could not delete this organization.',
  fields: { name: 'Organization name', type: 'Organization type', registrationNumber: 'Registration number', phone: 'Phone', email: 'Email' },
  placeholders: { name: 'e.g. Gasaka Tea Cooperative', email: 'organization@example.com' },
  validation: { nameRequired: 'Organization name is required.', invalid: 'Check the organization details and location hierarchy.' },
};
en.organizationTypes = { cooperative: 'Cooperative', farmer_group: 'Farmer Group', sme: 'SME', school: 'School', association: 'Association', ngo: 'NGO', other: 'Other' };
en.locations = {
  district: 'District', sector: 'Sector', cell: 'Cell', village: 'Village',
  selectDistrict: 'Select district...', selectSector: 'Select sector...', selectCell: 'Select cell...', selectVillage: 'Select village...',
  selectDistrictFirst: 'Select a district first.', selectSectorFirst: 'Select a sector first.', selectCellFirst: 'Select a cell first.',
  loadingDistricts: 'Loading districts...', loadingSectors: 'Loading sectors...', loadingCells: 'Loading cells...', loadingVillages: 'Loading villages...',
  savedValue: 'saved value', loadError: 'Could not load Rwanda locations.',
  incomplete: 'Select a district, sector, and cell in order.', farmerIncomplete: 'Select a district, sector, cell, and village in order.',
  legacyPreserved: 'Saved legacy location: {{location}}. It will be preserved unless you select a complete new location.',
};
en.locations.memberIncomplete = 'Select a district, sector, cell, and village for the member address.';
en.validation = {
  phonePlaceholder: '78X XXX XXX', phoneValid: 'Valid Rwanda phone number.', phoneRequired: 'Enter 9 local digits.',
  phoneOptional: 'Optional — enter 9 local digits.', phoneRemaining: '{{count}} digit(s) remaining.',
  phoneInvalid: 'Enter exactly 9 local digits after +250.', emailValid: 'Valid email address.',
  emailInvalid: 'Enter a complete email address, for example organization@example.com.',
};
en.members = {
  add: 'Add member', edit: 'Edit member', adding: 'Adding...', loading: 'Loading members...', loadError: 'Could not load members.',
  created: 'Member created successfully.', createError: 'Could not add member. Check the details and try again.',
  searchPlaceholder: 'Search by name, National ID, or phone...', noSearchResults: 'No members match your search.',
  empty: 'No members yet — add your first one.', farmerProfile: 'Farmer profile', notFarmer: 'Not a farmer',
  fields: { name: 'Name', firstName: 'First name', lastName: 'Last name', nationalId: 'National ID', gender: 'Gender', phone: 'Phone', address: 'Address', membershipDate: 'Membership date' },
  placeholders: { nationalId: '16-digit National ID', address: 'Village, cell, or street address' },
  gender: { notSpecified: 'Not specified', male: 'Male', female: 'Female', other: 'Other' },
  validation: { namesRequired: 'First name and last name are required.', firstNameRequired: 'First name is required.', lastNameRequired: 'Last name is required.', nationalIdInvalid: 'National ID must contain exactly 16 digits.' },
};
en.members.fields.residentialAddress = 'Residential/contact address';
en.members.fields.addressDetails = 'Additional address details';
en.members.placeholders.address = 'Street, building, or saved address detail';
en.members.addressHierarchyHint = 'Select the member residence from district through village.';
en.members.legacyAddressHint = 'Existing address details are preserved and remain separate from farm location.';
en.memberDetail = {
  back: 'Back to members', details: 'Member details', loadError: 'Could not load this member.', notFound: 'Member not found.',
  updated: 'Member details updated successfully.', saveError: 'Could not save these changes.',
  deleteConfirm: 'Delete {{name}}? This also removes their farmer profile where permitted and cannot be undone.',
  deleteError: 'Could not delete this member.',
};
en.farmers = {
  profile: 'Farmer profile', addProfile: 'Add farmer profile', noProfile: "This member doesn't have a farmer profile yet.",
  loading: 'Loading farmers...', loadError: 'Could not load farmers.', empty: "No farmer profiles yet. Add one from a member's detail page.",
  created: 'Farmer profile created successfully.', updated: 'Farmer profile updated successfully.', saveError: 'Could not save this farmer profile.',
  fields: { cropType: 'Crop type', farmSize: 'Farm size', farmSizeUnit: 'Farm size unit', location: 'Farm location' },
  placeholders: { cropType: 'e.g. Coffee' },
  units: { ha: 'Hectares (ha)', acres: 'Acres', m2: 'Square meters (m²)', km2: 'Square kilometers (km²)' },
  validation: { farmSizeInvalid: 'Enter a positive numeric farm size.', farmSizeUnitRequired: 'Select a valid farm size unit.', invalid: 'Check the crop, farm size, unit, and complete location hierarchy.' },
};
en.farmers.fields.member = 'Select member';
en.farmers.selectMember = 'Select a member...';
en.farmers.noEligibleMembers = 'No members without a Farmer Profile are available in this organization.';
en.farmers.viewMembers = 'View members';
en.farmers.validation.memberRequired = 'Select an existing member.';
en.farmers.validation.alreadyExists = 'The selected member already has a Farmer Profile.';
en.farmers.empty = 'No Farmer Profiles yet. Add one for an existing member.';
en.contact = { title: 'Contact', subtitle: 'Contact SmartBridge Technologies Ltd.', email: 'Email', emailAction: 'Send Email', phone: 'Phone', phoneAction: 'Call Us', whatsapp: 'WhatsApp', whatsappAction: 'Chat on WhatsApp' };

Object.assign(rw.common, {
  cooperatives: 'Imiryango', organizations: 'Imiryango', contact: 'Twandikire', view: 'Reba',
  optional: 'Si ngombwa', saving: 'Birimo kubikwa...', farmer: 'Umuhinzi',
});
Object.assign(rw.dashboard, {
  subtitle: 'Dore uko ibikorwa by’umuryango wawe bihagaze ubu.', noCooperative: 'Nta muryango wahiswemo.',
  organizationWelcome: 'Murakaza neza muri {{organization}}',
});
Object.assign(rw.modules, {
  membersSubtitle: 'Abantu bose banditswe mu muryango wawe.', farmersSubtitle: 'Abanyamuryango bafite imyirondoro y’ubuhinzi.',
  financeSubtitle: 'Ibyinjira, ibyasohotse, ubwizigame n’inguzanyo by’umuryango wawe.',
  cooperativesSubtitle: 'Gucunga imiryango yose yanditswe kuri sisitemu.', teamSubtitle: 'Konti z’abakozi n’abahinzi b’umuryango wawe.',
});
Object.assign(rw.auth, {
  askAdmin: 'Saba umuyobozi w’umuryango',
  askAdminHint: 'Umuyobozi w’umuryango cyangwa umuyobozi wa SmartBridge Technologies Ltd ashobora kuriguhindurira.',
  adminResetInstructions: 'Vugana n’umuyobozi w’umuryango wawe cyangwa umuyobozi mukuru wa SmartBridge Technologies Ltd. Kuri Konti z’Abakozi bashobora kuguhindurira ijambobanga.',
});
Object.assign(rw.production, {
  productionMode: 'Uburyo bw’umusaruro', individual: 'Umuntu ku giti cye', group: 'Itsinda', producer: 'Uwatanze umusaruro',
  farmerGroup: 'Itsinda ry’abahinzi', selectFarmerGroup: 'Hitamo itsinda ry’abahinzi…',
  productionGroup: 'Itsinda ritanga umusaruro', selectProductionGroup: 'Hitamo itsinda ritanga umusaruro…',
  selectOrganization: 'Hitamo umuryango mbere yo kongeramo umusaruro.',
  cropType: 'Ubwoko bw’igihingwa', selectCropType: 'Hitamo igihingwa…', addCropType: 'Cyangwa andika igihingwa gishya',
  expectedProduction: 'Umusaruro witezwe', actualHarvest: 'Umusaruro wabonetse', harvestDate: 'Itariki yo gusarura',
  productionLocation: 'Aho ubuhinzi cyangwa umusaruro ukorerwa', notes: 'Ibisobanuro', activeProducers: 'Abatanga umusaruro bakora',
  subtitle: 'Inyandiko z’umusaruro n’imikorere mu muryango wawe.',
  cooperativeComparison: 'Igereranya ry’imiryango',
});
rw.reports.cooperative = 'Umuryango';
rw.organizations = {
  subtitle: 'Gucunga imiryango yose yanditswe kuri sisitemu.', add: 'Ongeraho Umuryango', edit: 'Hindura Umuryango',
  details: 'Amakuru y’umuryango', create: 'Kora Umuryango', saveChanges: 'Bika impinduka', loading: 'Imiryango irimo gutegurwa...',
  empty: 'Nta muryango uraboneka — ongeraho uwa mbere.', noneShort: 'Nta muryango uraboneka', select: 'Hitamo umuryango',
  switch: 'Hindukira kuri uyu muryango', current: 'Uwo uri kureba', created: 'Umuryango wongewe neza.', updated: 'Umuryango wahinduwe neza.',
  deleted: 'Umuryango wasibwe neza.', saveError: 'Ntibyashobotse kubika uyu muryango. Reba amakuru wongere ugerageze.',
  deleteConfirm: 'Siba {{name}}? Biremewe gusa niba nta makuru afitanye isano na wo.',
  deleteBlocked: 'Uyu muryango ntushobora gusibwa kuko ufite abanyamuryango, abakoresha cyangwa andi makuru awufitanye isano.',
  deleteError: 'Ntibyashobotse gusiba uyu muryango.',
  fields: { name: 'Izina ry’umuryango', type: 'Ubwoko bw’umuryango', registrationNumber: 'Nomero yo kwandikisha', phone: 'Telefone', email: 'Imeyili' },
  placeholders: { name: 'urugero: Koperative y’Icyayi ya Gasaka', email: 'umuryango@example.com' },
  validation: { nameRequired: 'Izina ry’umuryango rirakenewe.', invalid: 'Reba amakuru y’umuryango n’aho uherereye.' },
};
rw.organizationTypes = { cooperative: 'Koperative', farmer_group: 'Itsinda ry’abahinzi', sme: 'Ikigo giciriritse', school: 'Ishuri', association: 'Ishyirahamwe', ngo: 'Umuryango utegamiye kuri Leta', other: 'Ikindi' };
rw.locations = {
  district: 'Akarere', sector: 'Umurenge', cell: 'Akagari', village: 'Umudugudu',
  selectDistrict: 'Hitamo akarere...', selectSector: 'Hitamo umurenge...', selectCell: 'Hitamo akagari...', selectVillage: 'Hitamo umudugudu...',
  selectDistrictFirst: 'Banza uhitemo akarere.', selectSectorFirst: 'Banza uhitemo umurenge.', selectCellFirst: 'Banza uhitemo akagari.',
  loadingDistricts: 'Uturere turimo gutegurwa...', loadingSectors: 'Imirenge irimo gutegurwa...', loadingCells: 'Utugari turimo gutegurwa...', loadingVillages: 'Imidugudu irimo gutegurwa...',
  savedValue: 'agaciro kabitswe', loadError: 'Ntibyashobotse kubona ahantu ho mu Rwanda.',
  incomplete: 'Hitamo akarere, umurenge n’akagari uko bikurikirana.', farmerIncomplete: 'Hitamo akarere, umurenge, akagari n’umudugudu uko bikurikirana.',
  legacyPreserved: 'Aho byari bisanzwe bibitswe: {{location}}. Hazagumaho keretse uhisemo ahandi huzuye.',
};
rw.locations.memberIncomplete = 'Hitamo akarere, umurenge, akagari n\'umudugudu by\'aderesi y\'umunyamuryango.';
rw.validation = {
  phonePlaceholder: '78X XXX XXX', phoneValid: 'Nomero ya telefone yo mu Rwanda ni nziza.', phoneRequired: 'Andika imibare 9.',
  phoneOptional: 'Si ngombwa — andika imibare 9.', phoneRemaining: 'Hasigaye imibare {{count}}.',
  phoneInvalid: 'Andika imibare 9 yuzuye nyuma ya +250.', emailValid: 'Imeyili ni nziza.',
  emailInvalid: 'Andika imeyili yuzuye, urugero umuryango@example.com.',
};
rw.members = {
  add: 'Ongeraho umunyamuryango', edit: 'Hindura umunyamuryango', adding: 'Birimo kongerwa...', loading: 'Abanyamuryango barimo gutegurwa...', loadError: 'Ntibyashobotse kubona abanyamuryango.',
  created: 'Umunyamuryango yongewe neza.', createError: 'Ntibyashobotse kongeraho umunyamuryango. Reba amakuru wongere ugerageze.',
  searchPlaceholder: 'Shakisha izina, indangamuntu cyangwa telefone...', noSearchResults: 'Nta munyamuryango uhuye n’ishakisha.', empty: 'Nta banyamuryango baraboneka — ongeraho uwa mbere.',
  farmerProfile: 'Umwirondoro w’umuhinzi', notFarmer: 'Si umuhinzi',
  fields: { name: 'Izina', firstName: 'Izina bwite', lastName: 'Izina ry’umuryango', nationalId: 'Indangamuntu', gender: 'Igitsina', phone: 'Telefone', address: 'Aderesi', membershipDate: 'Itariki yo kuba umunyamuryango' },
  placeholders: { nationalId: 'Imibare 16 y’indangamuntu', address: 'Umudugudu, akagari cyangwa umuhanda' },
  gender: { notSpecified: 'Nticyavuzwe', male: 'Gabo', female: 'Gore', other: 'Ikindi' },
  validation: { namesRequired: 'Izina bwite n’izina ry’umuryango birakenewe.', firstNameRequired: 'Izina bwite rirakenewe.', lastNameRequired: 'Izina ry’umuryango rirakenewe.', nationalIdInvalid: 'Indangamuntu igomba kuba igizwe n’imibare 16 gusa.' },
};
rw.members.fields.residentialAddress = 'Aderesi y\'aho umunyamuryango atuye';
rw.members.fields.addressDetails = 'Ibindi bisobanuro bya aderesi';
rw.members.placeholders.address = 'Umuhanda, inyubako cyangwa aderesi yari isanzwe ibitswe';
rw.members.addressHierarchyHint = 'Hitamo aho umunyamuryango atuye kuva ku karere kugera ku mudugudu.';
rw.members.legacyAddressHint = 'Aderesi yari isanzwe ibitswe iragumaho kandi itandukanye n\'aho umurima uherereye.';
rw.memberDetail = {
  back: 'Subira ku banyamuryango', details: 'Amakuru y’umunyamuryango', loadError: 'Ntibyashobotse kubona uyu munyamuryango.', notFound: 'Umunyamuryango ntiyabonetse.',
  updated: 'Amakuru y’umunyamuryango yahinduwe neza.', saveError: 'Ntibyashobotse kubika izi mpinduka.',
  deleteConfirm: 'Siba {{name}}? Umwirondoro we w’ubuhinzi na wo ushobora gusibwa kandi ntibishobora gusubizwa.', deleteError: 'Ntibyashobotse gusiba uyu munyamuryango.',
};
rw.farmers = {
  profile: 'Umwirondoro w’umuhinzi', addProfile: 'Ongeraho umwirondoro w’umuhinzi', noProfile: 'Uyu munyamuryango nta mwirondoro w’umuhinzi afite.',
  loading: 'Abahinzi barimo gutegurwa...', loadError: 'Ntibyashobotse kubona abahinzi.', empty: 'Nta myirondoro y’abahinzi iraboneka. Yongerere ku makuru y’umunyamuryango.',
  created: 'Umwirondoro w’umuhinzi wongewe neza.', updated: 'Umwirondoro w’umuhinzi wahinduwe neza.', saveError: 'Ntibyashobotse kubika umwirondoro w’umuhinzi.',
  fields: { cropType: 'Igihingwa', farmSize: 'Ingano y’umurima', farmSizeUnit: 'Igipimo cy’ingano y’umurima', location: 'Aho umurima uherereye' }, placeholders: { cropType: 'urugero: Ikawa' },
  units: { ha: 'Hegitari (ha)', acres: 'Acres', m2: 'Metero kare (m²)', km2: 'Kilometero kare (km²)' },
  validation: { farmSizeInvalid: 'Andika ingano y’umurima yemewe kandi irenze zeru.', farmSizeUnitRequired: 'Hitamo igipimo cyemewe cy’ingano y’umurima.', invalid: 'Reba igihingwa, ingano y’umurima, igipimo n’aho umurima uherereye huzuye.' },
};
rw.farmers.fields.member = 'Hitamo umunyamuryango';
rw.farmers.selectMember = 'Hitamo umunyamuryango...';
rw.farmers.noEligibleMembers = 'Nta munyamuryango udafite umwirondoro w’umuhinzi uboneka muri uyu muryango.';
rw.farmers.viewMembers = 'Reba abanyamuryango';
rw.farmers.validation.memberRequired = 'Hitamo umunyamuryango usanzwe.';
rw.farmers.validation.alreadyExists = 'Umunyamuryango wahisemo asanzwe afite umwirondoro w’umuhinzi.';
rw.farmers.empty = 'Nta myirondoro y’abahinzi iraboneka. Ongeraho umwirondoro ku munyamuryango usanzwe.';
rw.contact = { title: 'Twandikire', subtitle: 'Vugana na SmartBridge Technologies Ltd.', email: 'Imeyili', emailAction: 'Ohereza Imeyili', phone: 'Telefone', phoneAction: 'Duhamagare', whatsapp: 'WhatsApp', whatsappAction: 'Vugana natwe kuri WhatsApp' };

Object.assign(fr.common, {
  cooperatives: 'Organisations', organizations: 'Organisations', contact: 'Contact', view: 'Voir',
  optional: 'Facultatif', saving: 'Enregistrement...', farmer: 'Agriculteur',
});
Object.assign(fr.dashboard, {
  subtitle: 'Voici la situation actuelle de votre organisation.', noCooperative: 'Aucune organisation sélectionnée.',
  organizationWelcome: 'Bienvenue à {{organization}}',
});
Object.assign(fr.modules, {
  membersSubtitle: 'Toutes les personnes inscrites dans votre organisation.', farmersSubtitle: 'Membres ayant un profil agricole.',
  financeSubtitle: 'Revenus, dépenses, épargne et prêts de votre organisation.',
  cooperativesSubtitle: 'Gérez toutes les organisations inscrites sur la plateforme.', teamSubtitle: 'Comptes du personnel et des agriculteurs de votre organisation.',
});
Object.assign(fr.auth, {
  askAdmin: 'Demander à l’administrateur de votre organisation',
  askAdminHint: 'Le gestionnaire de votre organisation ou un administrateur de SmartBridge Technologies Ltd peut le réinitialiser.',
  adminResetInstructions: 'Contactez le gestionnaire de votre organisation ou le super administrateur de SmartBridge Technologies Ltd. Depuis Comptes du personnel, il peut réinitialiser votre mot de passe.',
});
Object.assign(fr.production, {
  productionMode: 'Mode de production', individual: 'Individuel', group: 'Groupe', producer: 'Producteur',
  farmerGroup: 'Groupement d’agriculteurs', selectFarmerGroup: 'Sélectionner un groupement…',
  productionGroup: 'Groupe de production', selectProductionGroup: 'Sélectionner un groupe de production…',
  selectOrganization: 'Sélectionnez une organisation avant d’ajouter une production.',
  cropType: 'Type de culture', selectCropType: 'Sélectionner une culture…', addCropType: 'Ou saisir une nouvelle culture',
  expectedProduction: 'Production prévue', actualHarvest: 'Récolte réelle', harvestDate: 'Date de récolte',
  productionLocation: 'Lieu agricole / de production', notes: 'Notes', activeProducers: 'Producteurs actifs',
  subtitle: 'Récoltes et performances de votre organisation.',
  cooperativeComparison: 'Comparaison des organisations',
});
fr.reports.cooperative = 'Organisation';
fr.organizations = {
  subtitle: 'Gérez toutes les organisations inscrites sur la plateforme.', add: 'Ajouter une organisation', edit: 'Modifier l’organisation',
  details: 'Détails de l’organisation', create: 'Créer l’organisation', saveChanges: 'Enregistrer les modifications', loading: 'Chargement des organisations...',
  empty: 'Aucune organisation — ajoutez la première.', noneShort: 'Aucune organisation', select: 'Sélectionner une organisation',
  switch: 'Basculer vers cette organisation', current: 'Organisation actuelle', created: 'Organisation créée avec succès.', updated: 'Organisation mise à jour avec succès.',
  deleted: 'Organisation supprimée avec succès.', saveError: 'Impossible d’enregistrer cette organisation. Vérifiez les informations.',
  deleteConfirm: 'Supprimer {{name}} ? Cela est permis uniquement si l’organisation ne contient aucune donnée liée.',
  deleteBlocked: 'Cette organisation ne peut pas être supprimée car elle contient des membres, utilisateurs ou autres données liées.',
  deleteError: 'Impossible de supprimer cette organisation.',
  fields: { name: 'Nom de l’organisation', type: 'Type d’organisation', registrationNumber: 'Numéro d’enregistrement', phone: 'Téléphone', email: 'E-mail' },
  placeholders: { name: 'p. ex. Coopérative de thé de Gasaka', email: 'organisation@example.com' },
  validation: { nameRequired: 'Le nom de l’organisation est obligatoire.', invalid: 'Vérifiez les informations et la hiérarchie administrative.' },
};
fr.organizationTypes = { cooperative: 'Coopérative', farmer_group: 'Groupement d’agriculteurs', sme: 'PME', school: 'École', association: 'Association', ngo: 'ONG', other: 'Autre' };
fr.locations = {
  district: 'District', sector: 'Secteur', cell: 'Cellule', village: 'Village',
  selectDistrict: 'Sélectionner le district...', selectSector: 'Sélectionner le secteur...', selectCell: 'Sélectionner la cellule...', selectVillage: 'Sélectionner le village...',
  selectDistrictFirst: 'Sélectionnez d’abord un district.', selectSectorFirst: 'Sélectionnez d’abord un secteur.', selectCellFirst: 'Sélectionnez d’abord une cellule.',
  loadingDistricts: 'Chargement des districts...', loadingSectors: 'Chargement des secteurs...', loadingCells: 'Chargement des cellules...', loadingVillages: 'Chargement des villages...',
  savedValue: 'valeur enregistrée', loadError: 'Impossible de charger les localités du Rwanda.',
  incomplete: 'Sélectionnez successivement un district, un secteur et une cellule.', farmerIncomplete: 'Sélectionnez successivement un district, un secteur, une cellule et un village.',
  legacyPreserved: 'Ancienne localisation enregistrée : {{location}}. Elle sera conservée sauf si vous sélectionnez une nouvelle localisation complète.',
};
fr.locations.memberIncomplete = 'Sélectionnez un district, un secteur, une cellule et un village pour l’adresse du membre.';
fr.validation = {
  phonePlaceholder: '78X XXX XXX', phoneValid: 'Numéro rwandais valide.', phoneRequired: 'Saisissez 9 chiffres locaux.',
  phoneOptional: 'Facultatif — saisissez 9 chiffres locaux.', phoneRemaining: 'Il reste {{count}} chiffre(s).',
  phoneInvalid: 'Saisissez exactement 9 chiffres après +250.', emailValid: 'Adresse e-mail valide.',
  emailInvalid: 'Saisissez une adresse complète, par exemple organisation@example.com.',
};
fr.members = {
  add: 'Ajouter un membre', edit: 'Modifier le membre', adding: 'Ajout...', loading: 'Chargement des membres...', loadError: 'Impossible de charger les membres.',
  created: 'Membre ajouté avec succès.', createError: 'Impossible d’ajouter le membre. Vérifiez les informations.',
  searchPlaceholder: 'Rechercher par nom, numéro d’identité ou téléphone...', noSearchResults: 'Aucun membre ne correspond à la recherche.', empty: 'Aucun membre — ajoutez le premier.',
  farmerProfile: 'Profil agricole', notFarmer: 'Pas agriculteur',
  fields: { name: 'Nom', firstName: 'Prénom', lastName: 'Nom', nationalId: 'Numéro d’identité nationale', gender: 'Genre', phone: 'Téléphone', address: 'Adresse', membershipDate: 'Date d’adhésion' },
  placeholders: { nationalId: 'Numéro d’identité à 16 chiffres', address: 'Village, cellule ou rue' },
  gender: { notSpecified: 'Non précisé', male: 'Homme', female: 'Femme', other: 'Autre' },
  validation: { namesRequired: 'Le prénom et le nom sont obligatoires.', firstNameRequired: 'Le prénom est obligatoire.', lastNameRequired: 'Le nom est obligatoire.', nationalIdInvalid: 'Le numéro d’identité nationale doit contenir exactement 16 chiffres.' },
};
fr.members.fields.residentialAddress = 'Adresse résidentielle/de contact';
fr.members.fields.addressDetails = 'Détails supplémentaires de l’adresse';
fr.members.placeholders.address = 'Rue, bâtiment ou ancienne adresse enregistrée';
fr.members.addressHierarchyHint = 'Sélectionnez la résidence du membre du district jusqu’au village.';
fr.members.legacyAddressHint = 'L’ancienne adresse est conservée et reste distincte de l’emplacement agricole.';
fr.memberDetail = {
  back: 'Retour aux membres', details: 'Détails du membre', loadError: 'Impossible de charger ce membre.', notFound: 'Membre introuvable.',
  updated: 'Membre mis à jour avec succès.', saveError: 'Impossible d’enregistrer ces modifications.',
  deleteConfirm: 'Supprimer {{name}} ? Son profil agricole sera aussi supprimé lorsque permis. Cette action est irréversible.', deleteError: 'Impossible de supprimer ce membre.',
};
fr.farmers = {
  profile: 'Profil agricole', addProfile: 'Ajouter un profil agricole', noProfile: 'Ce membre n’a pas encore de profil agricole.',
  loading: 'Chargement des agriculteurs...', loadError: 'Impossible de charger les agriculteurs.', empty: 'Aucun profil agricole. Ajoutez-en un depuis la fiche d’un membre.',
  created: 'Profil agricole créé avec succès.', updated: 'Profil agricole mis à jour avec succès.', saveError: 'Impossible d’enregistrer ce profil agricole.',
  fields: { cropType: 'Type de culture', farmSize: 'Superficie', farmSizeUnit: 'Unité de superficie', location: 'Localisation de la ferme' }, placeholders: { cropType: 'p. ex. Café' },
  units: { ha: 'Hectares (ha)', acres: 'Acres', m2: 'Mètres carrés (m²)', km2: 'Kilomètres carrés (km²)' },
  validation: { farmSizeInvalid: 'Saisissez une superficie numérique positive.', farmSizeUnitRequired: 'Sélectionnez une unité de superficie valide.', invalid: 'Vérifiez la culture, la superficie, l’unité et la hiérarchie complète du lieu.' },
};
fr.farmers.fields.member = 'Sélectionner un membre';
fr.farmers.selectMember = 'Sélectionner un membre...';
fr.farmers.noEligibleMembers = 'Aucun membre sans profil agricole n’est disponible dans cette organisation.';
fr.farmers.viewMembers = 'Voir les membres';
fr.farmers.validation.memberRequired = 'Sélectionnez un membre existant.';
fr.farmers.validation.alreadyExists = 'Le membre sélectionné possède déjà un profil agricole.';
fr.farmers.empty = 'Aucun profil agricole. Ajoutez-en un à un membre existant.';
fr.contact = { title: 'Contact', subtitle: 'Contactez SmartBridge Technologies Ltd.', email: 'E-mail', emailAction: 'Envoyer un e-mail', phone: 'Téléphone', phoneAction: 'Nous appeler', whatsapp: 'WhatsApp', whatsappAction: 'Discuter sur WhatsApp' };

Object.assign(en.common, {
  farmerGroups: 'Farmer Groups', individualProduction: 'Individual Production', groupProduction: 'Group / Cooperative Production',
  documentCategories: 'Document Categories', expiringDocuments: 'Expiring Documents', reports: 'Reports',
  staffAccounts: 'Staff Accounts', subscription: 'Subscription', settings: 'Settings', active: 'Active', inactive: 'Inactive',
  pageNotFound: "This AgriBridge page doesn't exist.", backToDashboard: 'Back to AgriBridge dashboard',
});
Object.assign(rw.common, {
  farmerGroups: 'Amatsinda y’Abahinzi', individualProduction: 'Umusaruro w’Umuhinzi', groupProduction: 'Umusaruro w’Itsinda / Umuryango',
  documentCategories: 'Ibyiciro by’Inyandiko', expiringDocuments: 'Inyandiko Zigiye Kurangira', reports: 'Raporo',
  staffAccounts: 'Konti z’Abakozi', subscription: 'Ifatabuguzi', settings: 'Igenamiterere', active: 'Bikora', inactive: 'Ntibikora',
  pageNotFound: 'Uru rupapuro rwa AgriBridge ntirubaho.', backToDashboard: 'Subira ku rubuga rwa AgriBridge',
});
Object.assign(fr.common, {
  farmerGroups: 'Groupements d’agriculteurs', individualProduction: 'Production individuelle', groupProduction: 'Production de groupe / organisation',
  documentCategories: 'Catégories de documents', expiringDocuments: 'Documents arrivant à expiration', reports: 'Rapports',
  staffAccounts: 'Comptes du personnel', subscription: 'Abonnement', settings: 'Paramètres', active: 'Actif', inactive: 'Inactif',
  pageNotFound: "Cette page AgriBridge n’existe pas.", backToDashboard: 'Retour au tableau de bord AgriBridge',
});

en.branding = { productTagline: 'Cooperative and farmer management, connected.' };
rw.branding = { productTagline: 'Imicungire ihuza imiryango n’abahinzi.' };
fr.branding = { productTagline: 'La gestion connectée des organisations et des agriculteurs.' };
en.modules.staffSubtitle = 'Staff and farmer user accounts for your organization.';
rw.modules.staffSubtitle = 'Konti z’abakozi n’abahinzi b’umuryango wawe.';
fr.modules.staffSubtitle = 'Comptes du personnel et des agriculteurs de votre organisation.';

Object.assign(en.production, {
  cooperativeLevel: 'Organization-level production (no group)', groupPrimaryFarmerError: 'Group production cannot have a primary farmer.',
  variety: 'Variety', reportingPeriod: 'Reporting period', productionCategory: 'Production category', qualityGrade: 'Quality / grade',
  contributingFarmers: 'Contributing farmers', contributionHint: 'Optional. Automatic totals require every contribution to use the production unit.',
  addFarmer: 'Add farmer', noContributions: 'No farmer contributions added.', contributionQuantity: 'Contribution quantity', contributionTotal: 'Contribution total',
  storageAndSales: 'Storage and sales', storageLocation: 'Storage location', storageQuantity: 'Storage quantity', soldQuantity: 'Sold quantity', remainingQuantity: 'Remaining quantity', buyer: 'Buyer',
});
Object.assign(rw.production, {
  cooperativeLevel: 'Umusaruro w’umuryango (nta tsinda)', groupPrimaryFarmerError: 'Umusaruro w’itsinda ntugomba kugira umuhinzi umwe w’ibanze.',
  variety: 'Ubwoko bwihariye', reportingPeriod: 'Igihe cya raporo', productionCategory: 'Icyiciro cy’umusaruro', qualityGrade: 'Ubwiza / urwego',
  contributingFarmers: 'Abahinzi batanze umusaruro', contributionHint: 'Si ngombwa. Igiteranyo cyikora gusa iyo bose bakoresheje igipimo kimwe n’umusaruro.',
  addFarmer: 'Ongeraho umuhinzi', noContributions: 'Nta musanzu w’abahinzi urongerwamo.', contributionQuantity: 'Ingano y’umusanzu', contributionTotal: 'Igiteranyo cy’imisanzu',
  storageAndSales: 'Ububiko n’igurisha', storageLocation: 'Aho bibitswe', storageQuantity: 'Ingano ibitswe', soldQuantity: 'Ingano yagurishijwe', remainingQuantity: 'Ingano isigaye', buyer: 'Umuguzi',
});
Object.assign(fr.production, {
  cooperativeLevel: 'Production de l’organisation (sans groupe)', groupPrimaryFarmerError: 'La production de groupe ne peut pas avoir un agriculteur principal.',
  variety: 'Variété', reportingPeriod: 'Période de rapport', productionCategory: 'Catégorie de production', qualityGrade: 'Qualité / grade',
  contributingFarmers: 'Agriculteurs contributeurs', contributionHint: 'Facultatif. Le total automatique exige la même unité que la production.',
  addFarmer: 'Ajouter un agriculteur', noContributions: 'Aucune contribution ajoutée.', contributionQuantity: 'Quantité contribuée', contributionTotal: 'Total des contributions',
  storageAndSales: 'Stockage et ventes', storageLocation: 'Lieu de stockage', storageQuantity: 'Quantité stockée', soldQuantity: 'Quantité vendue', remainingQuantity: 'Quantité restante', buyer: 'Acheteur',
});

en.farmerGroups = {
  title: 'Farmer Groups', subtitle: 'Organization-owned groups for collective production.', add: 'Add farmer group', edit: 'Edit farmer group',
  name: 'Group name', location: 'Location', empty: 'No farmer groups have been configured.', loadError: 'Could not load farmer groups.',
  saveError: 'Could not save this farmer group.', deleteConfirm: 'Delete {{name}}?', deleteError: 'Could not delete this farmer group.',
};
rw.farmerGroups = {
  title: 'Amatsinda y’Abahinzi', subtitle: 'Amatsinda y’umuryango akoreshwa mu musaruro rusange.', add: 'Ongeraho itsinda', edit: 'Hindura itsinda',
  name: 'Izina ry’itsinda', location: 'Aho riherereye', empty: 'Nta tsinda ry’abahinzi rirashyirwaho.', loadError: 'Ntibyashobotse kubona amatsinda.',
  saveError: 'Ntibyashobotse kubika itsinda.', deleteConfirm: 'Siba {{name}}?', deleteError: 'Ntibyashobotse gusiba itsinda.',
};
fr.farmerGroups = {
  title: 'Groupements d’agriculteurs', subtitle: 'Groupes appartenant à l’organisation pour la production collective.', add: 'Ajouter un groupement', edit: 'Modifier le groupement',
  name: 'Nom du groupe', location: 'Emplacement', empty: 'Aucun groupement configuré.', loadError: 'Impossible de charger les groupements.',
  saveError: 'Impossible d’enregistrer ce groupement.', deleteConfirm: 'Supprimer {{name}} ?', deleteError: 'Impossible de supprimer ce groupement.',
};

en.team = {
  title: 'TEAM', subtitle: 'Meet the Team Behind SmartBridge Technologies', add: 'Add member', edit: 'Edit member',
  emptyTitle: 'No team members configured', emptyBody: 'Real names, biographies, photos, and contact details have not been provided. A Super Admin can add verified personnel without fabricated information.',
  fullName: 'Full name', position: 'Position', biography: 'Short biography', responsibilities: 'Responsibilities', skills: 'Skills / expertise',
  photoUrl: 'Profile photo URL', email: 'Email', displayOrder: 'Display order', onePerLine: 'One item per line', loadError: 'Could not load team members.',
  saveError: 'Could not save this team member.', deleteConfirm: 'Delete {{name}}?', deleteError: 'Could not delete this team member.',
};
rw.team = {
  title: 'ITSINDA', subtitle: 'Menya Itsinda rya SmartBridge Technologies', add: 'Ongeraho umuntu', edit: 'Hindura umuntu',
  emptyTitle: 'Nta bagize itsinda barashyirwaho', emptyBody: 'Amazina nyayo, imyirondoro, amafoto n’aho kubariza ntibiratangazwa. Umuyobozi mukuru ashobora kongeramo amakuru yemejwe atabanje guhimba.',
  fullName: 'Amazina yose', position: 'Umwanya', biography: 'Umwirondoro mugufi', responsibilities: 'Inshingano', skills: 'Ubumenyi / ubuhanga',
  photoUrl: 'Ihuza ry’ifoto', email: 'Imeyili', displayOrder: 'Uko bakurikirana', onePerLine: 'Kimwe kuri buri murongo', loadError: 'Ntibyashobotse kubona abagize itsinda.',
  saveError: 'Ntibyashobotse kubika ugize itsinda.', deleteConfirm: 'Siba {{name}}?', deleteError: 'Ntibyashobotse gusiba ugize itsinda.',
};
fr.team = {
  title: 'ÉQUIPE', subtitle: 'Découvrez l’équipe derrière SmartBridge Technologies', add: 'Ajouter un membre', edit: 'Modifier le membre',
  emptyTitle: 'Aucun membre configuré', emptyBody: 'Les noms, biographies, photos et coordonnées réels n’ont pas été fournis. Un Super Admin peut ajouter des informations vérifiées sans en inventer.',
  fullName: 'Nom complet', position: 'Poste', biography: 'Courte biographie', responsibilities: 'Responsabilités', skills: 'Compétences / expertise',
  photoUrl: 'URL de la photo', email: 'E-mail', displayOrder: 'Ordre d’affichage', onePerLine: 'Un élément par ligne', loadError: 'Impossible de charger l’équipe.',
  saveError: 'Impossible d’enregistrer ce membre.', deleteConfirm: 'Supprimer {{name}} ?', deleteError: 'Impossible de supprimer ce membre.',
};

Object.assign(en.team, {
  personalInformation: 'Personal information', professionalInformation: 'Professional information', officialRole: 'Official role',
  selectOfficialRole: 'Select an official role…', profileVisibility: 'Profile visibility', profileStatus: 'Profile status', visible: 'Visible', hidden: 'Hidden',
  viewProfile: 'View profile', systemAccess: 'System access', systemAccessHelp: 'A Team profile can exist without a login. Link an existing account only when this person needs application access.',
  linkedAccount: 'Linked user account', noLinkedAccount: 'No linked account — profile only', notLinked: 'Not linked', enabled: 'Enabled', disabled: 'Disabled',
  accountStatus: 'Account status', assignedSystemRole: 'Assigned system role', systemRole: 'System role', permissions: 'Permissions', accessibleModules: 'Accessible modules',
  accessStatus: 'Access status', viewPermission: 'View', managePermission: 'Manage', noAccessibleModules: 'No modules selected',
  photoUrlInvalid: 'Profile Photo URL must be a valid HTTPS image URL.', accessChangeConfirm: 'This change reduces or disables account access. Continue?',
  archive: 'Archive profile', archiveConfirm: 'Archive {{name}}? The record will be retained but hidden and marked inactive.', archiveError: 'Could not archive this Team profile.',
  modules: { dashboard: 'Dashboard', team: 'Team', organizations: 'Organizations', farmers: 'Farmers', members: 'Members', production: 'Production', inventory: 'Inventory', finance: 'Finance', payroll: 'Payroll', documents: 'Documents', reports: 'Reports', settings: 'Settings', users: 'User management' },
});
Object.assign(rw.team, {
  personalInformation: 'Amakuru bwite', professionalInformation: 'Amakuru y’umwuga', officialRole: 'Inshingano yemewe',
  selectOfficialRole: 'Hitamo inshingano yemewe…', profileVisibility: 'Kugaragara k’umwirondoro', profileStatus: 'Imimerere y’umwirondoro', visible: 'Uragaragara', hidden: 'Uhishwe',
  viewProfile: 'Reba umwirondoro', systemAccess: 'Uburenganzira bwa sisitemu', systemAccessHelp: 'Umwirondoro w’ugize itsinda ushobora kubaho nta konti. Huza konti iriho gusa igihe uyu muntu akeneye gukoresha porogaramu.',
  linkedAccount: 'Konti ihujwe', noLinkedAccount: 'Nta konti ihujwe — umwirondoro gusa', notLinked: 'Ntiyahujwe', enabled: 'Burafunguye', disabled: 'Burafunze',
  accountStatus: 'Imimerere ya konti', assignedSystemRole: 'Uruhare rwa sisitemu', systemRole: 'Uruhare rwa sisitemu', permissions: 'Uburenganzira', accessibleModules: 'Ibice byemewe',
  accessStatus: 'Imimerere y’uburenganzira', viewPermission: 'Kureba', managePermission: 'Gucunga', noAccessibleModules: 'Nta gice cyatoranyijwe',
  photoUrlInvalid: 'Ihuza ry’ifoto rigomba kuba URL ya HTTPS yemewe.', accessChangeConfirm: 'Iri hinduka riragabanya cyangwa rigafunga uburenganzira bwa konti. Komeza?',
  archive: 'Bika umwirondoro', archiveConfirm: 'Bika umwirondoro wa {{name}}? Amakuru azagumaho ariko ahishwe kandi adakora.', archiveError: 'Ntibyashobotse kubika uyu mwirondoro.',
  modules: { dashboard: 'Imbonerahamwe', team: 'Itsinda', organizations: 'Imiryango', farmers: 'Abahinzi', members: 'Abanyamuryango', production: 'Umusaruro', inventory: 'Ububiko', finance: 'Imari', payroll: 'Imishahara', documents: 'Inyandiko', reports: 'Raporo', settings: 'Igenamiterere', users: 'Imicungire y’abakoresha' },
});
Object.assign(fr.team, {
  personalInformation: 'Informations personnelles', professionalInformation: 'Informations professionnelles', officialRole: 'Rôle officiel',
  selectOfficialRole: 'Sélectionner un rôle officiel…', profileVisibility: 'Visibilité du profil', profileStatus: 'Statut du profil', visible: 'Visible', hidden: 'Masqué',
  viewProfile: 'Voir le profil', systemAccess: 'Accès au système', systemAccessHelp: 'Un profil d’équipe peut exister sans connexion. Liez un compte existant uniquement si cette personne doit accéder à l’application.',
  linkedAccount: 'Compte utilisateur lié', noLinkedAccount: 'Aucun compte lié — profil uniquement', notLinked: 'Non lié', enabled: 'Activé', disabled: 'Désactivé',
  accountStatus: 'Statut du compte', assignedSystemRole: 'Rôle système attribué', systemRole: 'Rôle système', permissions: 'Autorisations', accessibleModules: 'Modules accessibles',
  accessStatus: 'Statut d’accès', viewPermission: 'Voir', managePermission: 'Gérer', noAccessibleModules: 'Aucun module sélectionné',
  photoUrlInvalid: 'L’URL de la photo doit être une URL d’image HTTPS valide.', accessChangeConfirm: 'Cette modification réduit ou désactive l’accès au compte. Continuer ?',
  archive: 'Archiver le profil', archiveConfirm: 'Archiver {{name}} ? Le dossier sera conservé, masqué et marqué inactif.', archiveError: 'Impossible d’archiver ce profil.',
  modules: { dashboard: 'Tableau de bord', team: 'Équipe', organizations: 'Organisations', farmers: 'Agriculteurs', members: 'Membres', production: 'Production', inventory: 'Stock', finance: 'Finance', payroll: 'Paie', documents: 'Documents', reports: 'Rapports', settings: 'Paramètres', users: 'Gestion des utilisateurs' },
});

en.access = { deniedTitle: 'Access restricted', deniedBody: 'Your account does not have permission to open this module.' };
rw.access = { deniedTitle: 'Uburenganzira burabujijwe', deniedBody: 'Konti yawe ntiyemerewe gufungura iki gice.' };
fr.access = { deniedTitle: 'Accès restreint', deniedBody: 'Votre compte n’est pas autorisé à ouvrir ce module.' };

en.subscription = {
  title: 'Subscription / Plans', subtitle: 'Review plan options and billing readiness for your organization.', loading: 'Loading subscription…', loadError: 'Could not load subscription information.',
  current: 'Current subscription', plan: 'Plan', billingCycle: 'Billing cycle', monthly: 'Monthly', yearly: 'Yearly', nextBilling: 'Next billing date', renewal: 'Renewal', ends: 'Ends after current period', paymentStatus: 'Payment status',
  noSubscription: 'No subscription is configured', noSubscriptionBody: 'Your organization has no billing record yet. Existing access is unchanged.', available: 'Available plans', pricingPending: 'Business pricing has not been finalized; no monetary values are shown.',
  contactPricing: 'Contact us for pricing', yearlyGuidance: 'Designed for a future {{minimum_percent}}–{{maximum_percent}}% annual discount.', configurable: 'Feature access can be configured centrally', organizationReady: 'Organization-owned subscription architecture', currentBadge: 'Current plan', upgrade: 'Request upgrade', downgrade: 'Request downgrade',
  requestBody: 'Please contact me about the {{plan}} plan with {{cycle}} billing.', history: 'Subscription history', invoices: 'Invoices & receipts', noHistory: 'No subscription history is available.', noInvoices: 'No paid invoices or receipts exist.',
  status: { trialing: 'Trialing', active: 'Active', past_due: 'Past due', cancelled: 'Cancelled', inactive: 'Inactive', not_required: 'Not required', pending: 'Pending', paid: 'Paid', failed: 'Failed', refunded: 'Refunded' },
  planNames: { free_trial: 'Free / Trial', basic: 'Basic', professional: 'Professional', enterprise: 'Enterprise' },
  planDescriptions: { free_trial: 'A starting plan for evaluating AgriBridge.', basic: 'Core organization, farmer, and record management.', professional: 'Expanded production, document, reporting, and team workflows.', enterprise: 'Configurable support for larger and multi-organization operations.' },
};
rw.subscription = {
  title: 'Ifatabuguzi / Gahunda', subtitle: 'Reba gahunda n’uko kwishyura bizategurwa ku muryango wawe.', loading: 'Ifatabuguzi ririmo gutegurwa…', loadError: 'Ntibyashobotse kubona amakuru y’ifatabuguzi.',
  current: 'Ifatabuguzi ririho', plan: 'Gahunda', billingCycle: 'Igihe cyo kwishyura', monthly: 'Buri kwezi', yearly: 'Buri mwaka', nextBilling: 'Itariki yo kwishyura ikurikira', renewal: 'Kuvugurura', ends: 'Rirangira iki gihe kirangiye', paymentStatus: 'Imimerere y’ubwishyu',
  noSubscription: 'Nta fatabuguzi rirashyirwaho', noSubscriptionBody: 'Umuryango wawe nta nyandiko y’ubwishyu ufite. Uburenganzira busanzwe ntibuhindutse.', available: 'Gahunda ziboneka', pricingPending: 'Ibiciro ntibirarangira; nta mafaranga mpimbano yerekanwa.',
  contactPricing: 'Twandikire ku biciro', yearlyGuidance: 'Yateguriwe ko buri mwaka hazagabanywa {{minimum_percent}}–{{maximum_percent}}%.', configurable: 'Uburenganzira bushobora kugenwa hamwe', organizationReady: 'Ifatabuguzi rifitwe n’umuryango', currentBadge: 'Gahunda iriho', upgrade: 'Saba gahunda yo hejuru', downgrade: 'Saba gahunda yo hasi',
  requestBody: 'Mundebere amakuru ya gahunda {{plan}} yishyurwa {{cycle}}.', history: 'Amateka y’ifatabuguzi', invoices: 'Inyemezabuguzi n’inyemezabyishyuwe', noHistory: 'Nta mateka y’ifatabuguzi araboneka.', noInvoices: 'Nta nyemezabuguzi zishyuwe ziboneka.',
  status: { trialing: 'Igerageza', active: 'Rikora', past_due: 'Ubwishyu bwaratinze', cancelled: 'Ryahagaritswe', inactive: 'Ntirikora', not_required: 'Ntibikenewe', pending: 'Bitegereje', paid: 'Byishyuwe', failed: 'Byanze', refunded: 'Byasubijwe' },
  planNames: { free_trial: 'Ubuntu / Igerageza', basic: 'Ibanze', professional: 'Iy’umwuga', enterprise: 'Iy’ikigo kinini' },
  planDescriptions: { free_trial: 'Gahunda yo gutangira kugerageza AgriBridge.', basic: 'Imicungire y’ibanze y’umuryango n’abahinzi.', professional: 'Umusaruro, inyandiko, raporo n’itsinda byagutse.', enterprise: 'Imicungire ihindurwa ku miryango minini cyangwa myinshi.' },
};
fr.subscription = {
  title: 'Abonnement / Offres', subtitle: 'Consultez les offres et la préparation de la facturation de votre organisation.', loading: 'Chargement de l’abonnement…', loadError: 'Impossible de charger les informations d’abonnement.',
  current: 'Abonnement actuel', plan: 'Offre', billingCycle: 'Cycle de facturation', monthly: 'Mensuel', yearly: 'Annuel', nextBilling: 'Prochaine facturation', renewal: 'Renouvellement', ends: 'Prend fin après la période actuelle', paymentStatus: 'Statut du paiement',
  noSubscription: 'Aucun abonnement configuré', noSubscriptionBody: 'Votre organisation n’a pas encore de dossier de facturation. L’accès existant reste inchangé.', available: 'Offres disponibles', pricingPending: 'Les tarifs ne sont pas finalisés ; aucun montant fictif n’est affiché.',
  contactPricing: 'Nous contacter pour le tarif', yearlyGuidance: 'Prévu pour une remise annuelle future de {{minimum_percent}} à {{maximum_percent}} %.', configurable: 'Accès aux fonctionnalités configurable', organizationReady: 'Architecture d’abonnement par organisation', currentBadge: 'Offre actuelle', upgrade: 'Demander une mise à niveau', downgrade: 'Demander une réduction',
  requestBody: 'Veuillez me contacter au sujet de l’offre {{plan}} avec facturation {{cycle}}.', history: 'Historique des abonnements', invoices: 'Factures et reçus', noHistory: 'Aucun historique d’abonnement disponible.', noInvoices: 'Aucune facture ou reçu payé.',
  status: { trialing: 'Essai', active: 'Actif', past_due: 'En retard', cancelled: 'Annulé', inactive: 'Inactif', not_required: 'Non requis', pending: 'En attente', paid: 'Payé', failed: 'Échoué', refunded: 'Remboursé' },
  planNames: { free_trial: 'Gratuit / Essai', basic: 'Essentiel', professional: 'Professionnel', enterprise: 'Entreprise' },
  planDescriptions: { free_trial: 'Une offre de départ pour évaluer AgriBridge.', basic: 'Gestion essentielle des organisations et agriculteurs.', professional: 'Production, documents, rapports et équipes étendus.', enterprise: 'Support configurable pour les grandes opérations multi-organisations.' },
};

en.settings = { title: 'AgriBridge Settings', subtitle: 'Manage your language and account security.', language: 'Language', languageHint: 'Choose the language used throughout AgriBridge.', security: 'Account security', securityHint: 'Update your password using the existing secure workflow.' };
rw.settings = { title: 'Igenamiterere rya AgriBridge', subtitle: 'Gena ururimi n’umutekano wa konti.', language: 'Ururimi', languageHint: 'Hitamo ururimi rukoreshwa muri AgriBridge.', security: 'Umutekano wa konti', securityHint: 'Hindura ijambobanga ukoresheje uburyo busanzwe bwizewe.' };
fr.settings = { title: 'Paramètres AgriBridge', subtitle: 'Gérez votre langue et la sécurité du compte.', language: 'Langue', languageHint: 'Choisissez la langue utilisée dans AgriBridge.', security: 'Sécurité du compte', securityHint: 'Modifiez votre mot de passe avec le processus sécurisé existant.' };
Object.assign(en.reports, { hubTitle: 'AgriBridge Reports', hubSubtitle: 'Open a module to filter and export its live organization data.', openModule: 'Open the module and use its CSV, Excel, PDF, or print actions.', modules: { members: 'Member reports', production: 'Production reports', finance: 'Finance reports', inventory: 'Inventory reports', documents: 'Document records' } });
Object.assign(rw.reports, { hubTitle: 'Raporo za AgriBridge', hubSubtitle: 'Fungura igice uyungurure kandi wohereze amakuru nyayo y’umuryango.', openModule: 'Fungura igice ukoreshe CSV, Excel, PDF cyangwa gucapa.', modules: { members: 'Raporo z’abanyamuryango', production: 'Raporo z’umusaruro', finance: 'Raporo z’imari', inventory: 'Raporo z’ububiko', documents: 'Inyandiko' } });
Object.assign(fr.reports, { hubTitle: 'Rapports AgriBridge', hubSubtitle: 'Ouvrez un module pour filtrer et exporter ses données réelles.', openModule: 'Ouvrez le module et utilisez les actions CSV, Excel, PDF ou impression.', modules: { members: 'Rapports des membres', production: 'Rapports de production', finance: 'Rapports financiers', inventory: 'Rapports d’inventaire', documents: 'Registre documentaire' } });

en.contact.subtitle = 'Contact SmartBridge Technologies Ltd.';
rw.contact.subtitle = 'Vugana na SmartBridge Technologies Ltd.';
fr.contact.subtitle = 'Contactez SmartBridge Technologies Ltd.';
en.auth.askAdminHint = 'Your organization manager or SmartBridge Technologies Ltd administrator can reset it for you directly.';
en.auth.adminResetInstructions = 'Contact your organization manager or SmartBridge Technologies Ltd super admin. From Staff Accounts, they can reset your password and share a temporary one securely.';
rw.auth.askAdminHint = 'Umuyobozi w’umuryango cyangwa umuyobozi wa SmartBridge Technologies Ltd ashobora kuriguhindurira.';
rw.auth.adminResetInstructions = 'Vugana n’umuyobozi w’umuryango cyangwa umuyobozi mukuru wa SmartBridge Technologies Ltd. Kuri Konti z’Abakozi ashobora kuguhindurira ijambobanga.';
fr.auth.askAdminHint = 'Le gestionnaire de votre organisation ou un administrateur de SmartBridge Technologies Ltd peut le réinitialiser.';
fr.auth.adminResetInstructions = 'Contactez le gestionnaire de votre organisation ou le super administrateur de SmartBridge Technologies Ltd. Depuis Comptes du personnel, il peut réinitialiser votre mot de passe.';

Object.assign(en.documents, {
  title: 'Document Management', subtitle: 'Organize, protect, and monitor organization documents.', all: 'All Documents', categoriesTitle: 'Categories', expiring: 'Expiring Documents', add: 'Add Document',
  totalDocuments: 'Total Documents', meetingDocuments: 'Meeting Documents', legalDocuments: 'Legal Documents', financialDocuments: 'Financial Documents', expiringSoon: 'Expiring Soon',
  categoriesFor: 'Valid categories for {{type}}', search: 'Search title, file, description, or tags…', category: 'Document category', documentType: 'Document type',
  documentDate: 'Document date', expiryDate: 'Expiry date', uploadedBy: 'Uploaded by', clearFilters: 'Clear filters', noExpiring: 'No documents are expiring soon.',
  noCategoryResults: 'No documents match these category filters.', titleField: 'Document title', organizationOwner: 'Organization / owner', organization: 'Organization',
  editMetadata: 'Edit metadata', replaceFile: 'Replace file', archive: 'Archive', restore: 'Restore', attachTo: 'Attach to', version: 'Version', tags: 'Tags',
  tagsHint: 'Comma-separated tags', visibility: 'Visibility', notes: 'Notes', selectCategory: 'Select a category…', selectType: 'Select a document type…',
  classificationRequired: 'Select a valid document category and type.', expiryAfterDate: 'Expiry date cannot be before the document date.', updated: 'Document metadata updated.', replaced: 'Document file replaced.',
  replaceHint: 'Replace the file for “{{title}}” while preserving its metadata and ID.', archiveConfirm: 'Archive “{{name}}”?', restoreConfirm: 'Restore “{{name}}”?', actionError: 'Could not update this document.',
  ownerTypes: { cooperative: 'Organization', member: 'Member', farmer: 'Farmer', loan: 'Loan' },
  visibilityOptions: { organization: 'Organization users', restricted: 'Restricted roles' },
  status: { active: 'Active', expiring_soon: 'Expiring soon', expired: 'Expired', archived: 'Archived' },
  categories: { registration: 'Registration', governance: 'Governance', meetings: 'Meetings', membership: 'Membership', finance: 'Financial', strategy: 'Strategy & Planning', operations: 'Operations', legal: 'Legal & Compliance', people: 'People & Records', projects: 'Projects & Programs', education: 'Academic & School Records', other: 'Other' },
});
Object.assign(rw.documents, {
  title: 'Imicungire y’Inyandiko', subtitle: 'Tegura, urinde kandi ukurikirane inyandiko z’umuryango.', all: 'Inyandiko Zose', categoriesTitle: 'Ibyiciro', expiring: 'Izigiye Kurangira', add: 'Ongeraho Inyandiko',
  totalDocuments: 'Inyandiko Zose', meetingDocuments: 'Inyandiko z’Inama', legalDocuments: 'Inyandiko z’Amategeko', financialDocuments: 'Inyandiko z’Imari', expiringSoon: 'Izigiye Kurangira',
  categoriesFor: 'Ibyiciro byemewe kuri {{type}}', search: 'Shakisha umutwe, dosiye, ibisobanuro cyangwa ibirango…', category: 'Icyiciro cy’inyandiko', documentType: 'Ubwoko bw’inyandiko',
  documentDate: 'Itariki y’inyandiko', expiryDate: 'Itariki yo kurangira', uploadedBy: 'Yashyizweho na', clearFilters: 'Kuraho akayunguruzo', noExpiring: 'Nta nyandiko iri hafi kurangira.',
  noCategoryResults: 'Nta nyandiko ihuye n’ibi byiciro.', titleField: 'Umutwe w’inyandiko', organizationOwner: 'Umuryango / nyirayo', organization: 'Umuryango',
  editMetadata: 'Hindura amakuru', replaceFile: 'Simbuza dosiye', archive: 'Shyira mu bubiko', restore: 'Subiza', attachTo: 'Yomeke kuri', version: 'Verisiyo', tags: 'Ibirango',
  tagsHint: 'Tandukanya ibirango n’akitso', visibility: 'Abayibona', notes: 'Ibisobanuro', selectCategory: 'Hitamo icyiciro…', selectType: 'Hitamo ubwoko bw’inyandiko…',
  classificationRequired: 'Hitamo icyiciro n’ubwoko bw’inyandiko byemewe.', expiryAfterDate: 'Itariki yo kurangira ntishobora kubanziriza iy’inyandiko.', updated: 'Amakuru y’inyandiko yahinduwe.', replaced: 'Dosiye y’inyandiko yasimbujwe.',
  replaceHint: 'Simbuza dosiye ya “{{title}}” udahinduye amakuru n’indangamuntu yayo.', archiveConfirm: 'Shyira “{{name}}” mu bubiko?', restoreConfirm: 'Subiza “{{name}}”?', actionError: 'Ntibyashobotse guhindura iyi nyandiko.',
  ownerTypes: { cooperative: 'Umuryango', member: 'Umunyamuryango', farmer: 'Umuhinzi', loan: 'Inguzanyo' },
  visibilityOptions: { organization: 'Abakoresha b’umuryango', restricted: 'Inshingano zihariye' },
  status: { active: 'Irakora', expiring_soon: 'Igiye kurangira', expired: 'Yararangiye', archived: 'Mu bubiko' },
  categories: { registration: 'Iyandikisha', governance: 'Imiyoborere', meetings: 'Inama', membership: 'Abanyamuryango', finance: 'Imari', strategy: 'Ingamba n’Igenamigambi', operations: 'Ibikorwa', legal: 'Amategeko n’Iyubahiriza', people: 'Abantu n’Inyandiko', projects: 'Imishinga na Porogaramu', education: 'Amashuri n’Amasomo', other: 'Ibindi' },
});
Object.assign(fr.documents, {
  title: 'Gestion documentaire', subtitle: 'Organisez, protégez et suivez les documents de l’organisation.', all: 'Tous les documents', categoriesTitle: 'Catégories', expiring: 'Documents à expiration', add: 'Ajouter un document',
  totalDocuments: 'Total des documents', meetingDocuments: 'Documents de réunion', legalDocuments: 'Documents juridiques', financialDocuments: 'Documents financiers', expiringSoon: 'Expire bientôt',
  categoriesFor: 'Catégories valides pour {{type}}', search: 'Rechercher titre, fichier, description ou tags…', category: 'Catégorie', documentType: 'Type de document',
  documentDate: 'Date du document', expiryDate: 'Date d’expiration', uploadedBy: 'Téléversé par', clearFilters: 'Effacer les filtres', noExpiring: 'Aucun document n’expire bientôt.',
  noCategoryResults: 'Aucun document ne correspond à ces catégories.', titleField: 'Titre du document', organizationOwner: 'Organisation / propriétaire', organization: 'Organisation',
  editMetadata: 'Modifier les métadonnées', replaceFile: 'Remplacer le fichier', archive: 'Archiver', restore: 'Restaurer', attachTo: 'Rattacher à', version: 'Version', tags: 'Tags',
  tagsHint: 'Tags séparés par des virgules', visibility: 'Visibilité', notes: 'Notes', selectCategory: 'Sélectionner une catégorie…', selectType: 'Sélectionner un type…',
  classificationRequired: 'Sélectionnez une catégorie et un type valides.', expiryAfterDate: 'La date d’expiration ne peut pas précéder la date du document.', updated: 'Métadonnées mises à jour.', replaced: 'Fichier remplacé.',
  replaceHint: 'Remplacez le fichier de « {{title}} » en conservant ses métadonnées et son identifiant.', archiveConfirm: 'Archiver « {{name}} » ?', restoreConfirm: 'Restaurer « {{name}} » ?', actionError: 'Impossible de mettre à jour ce document.',
  ownerTypes: { cooperative: 'Organisation', member: 'Membre', farmer: 'Agriculteur', loan: 'Prêt' },
  visibilityOptions: { organization: 'Utilisateurs de l’organisation', restricted: 'Rôles restreints' },
  status: { active: 'Actif', expiring_soon: 'Expire bientôt', expired: 'Expiré', archived: 'Archivé' },
  categories: { registration: 'Enregistrement', governance: 'Gouvernance', meetings: 'Réunions', membership: 'Adhésion', finance: 'Financier', strategy: 'Stratégie et planification', operations: 'Opérations', legal: 'Juridique et conformité', people: 'Personnel et dossiers', projects: 'Projets et programmes', education: 'Dossiers scolaires et académiques', other: 'Autre' },
});

en.documents.types = {
  cooperative_registration_certificate: 'Cooperative Registration Certificate', certificates: 'Certificates', cooperative_bylaws_constitution: 'Cooperative Bylaws / Constitution', policies: 'Policies', general_assembly_minutes: 'General Assembly Minutes', board_meeting_minutes: 'Board Meeting Minutes', management_meeting_minutes: 'Management Meeting Minutes', meeting_agenda: 'Meeting Agenda', annual_general_meeting_documents: 'Annual General Meeting Documents', member_register: 'Member Register', membership_documents: 'Membership Documents', financial_reports: 'Financial Reports', audit_reports: 'Audit Reports', annual_reports: 'Annual Reports', strategic_plan: 'Strategic Plan', business_plan: 'Business Plan', production_reports: 'Production Reports', contracts_agreements: 'Contracts / Agreements', government_correspondence: 'Government Correspondence', group_registration: 'Group Registration', group_constitution: 'Group Constitution', group_rules: 'Group Rules', meeting_minutes: 'Meeting Minutes', attendance_records: 'Attendance Records', financial_records: 'Financial Records', production_records: 'Production Records', training_documents: 'Training Documents', agreements: 'Agreements', business_registration: 'Business Registration', business_license: 'Business License', company_policies: 'Company Policies', board_minutes: 'Board Minutes', financial_statements: 'Financial Statements', invoices: 'Invoices', tax_documents: 'Tax Documents', contracts: 'Contracts', compliance_documents: 'Compliance Documents', employee_documents: 'Employee Documents', registration_certificate: 'Registration Certificate', constitution: 'Constitution', project_documents: 'Project Documents', monitoring_evaluation_reports: 'Monitoring & Evaluation Reports', donor_agreements: 'Donor Agreements', registration_documents: 'Registration Documents', school_policies: 'School Policies', academic_reports: 'Academic Reports', student_records: 'Student Records', staff_documents: 'Staff Documents', bylaws: 'Bylaws', other: 'Other',
};
rw.documents.types = {
  cooperative_registration_certificate: 'Icyemezo cy’Iyandikisha rya Koperative', certificates: 'Impamyabushobozi', cooperative_bylaws_constitution: 'Amategeko Shingiro ya Koperative', policies: 'Politiki', general_assembly_minutes: 'Inyandiko z’Inteko Rusange', board_meeting_minutes: 'Inyandiko z’Inama y’Ubutegetsi', management_meeting_minutes: 'Inyandiko z’Inama y’Ubuyobozi', meeting_agenda: 'Gahunda y’Inama', annual_general_meeting_documents: 'Inyandiko z’Inteko Rusange y’Umwaka', member_register: 'Igitabo cy’Abanyamuryango', membership_documents: 'Inyandiko z’Ubunyamuryango', financial_reports: 'Raporo z’Imari', audit_reports: 'Raporo z’Ubugenzuzi', annual_reports: 'Raporo z’Umwaka', strategic_plan: 'Gahunda y’Ingamba', business_plan: 'Gahunda y’Ubucuruzi', production_reports: 'Raporo z’Umusaruro', contracts_agreements: 'Amasezerano', government_correspondence: 'Inyandiko z’Inzego za Leta', group_registration: 'Iyandikisha ry’Itsinda', group_constitution: 'Amategeko Shingiro y’Itsinda', group_rules: 'Amategeko y’Itsinda', meeting_minutes: 'Inyandiko z’Inama', attendance_records: 'Inyandiko z’Abitabiriye', financial_records: 'Inyandiko z’Imari', production_records: 'Inyandiko z’Umusaruro', training_documents: 'Inyandiko z’Amahugurwa', agreements: 'Amasezerano', business_registration: 'Iyandikisha ry’Ubucuruzi', business_license: 'Uruhushya rw’Ubucuruzi', company_policies: 'Politiki z’Ikigo', board_minutes: 'Inyandiko z’Inama y’Ubutegetsi', financial_statements: 'Imibare y’Imari', invoices: 'Inyemezabuguzi', tax_documents: 'Inyandiko z’Imisoro', contracts: 'Amasezerano', compliance_documents: 'Inyandiko z’Iyubahiriza', employee_documents: 'Inyandiko z’Abakozi', registration_certificate: 'Icyemezo cy’Iyandikisha', constitution: 'Amategeko Shingiro', project_documents: 'Inyandiko z’Imishinga', monitoring_evaluation_reports: 'Raporo z’Ikurikirana n’Isuzuma', donor_agreements: 'Amasezerano n’Abaterankunga', registration_documents: 'Inyandiko z’Iyandikisha', school_policies: 'Politiki z’Ishuri', academic_reports: 'Raporo z’Amasomo', student_records: 'Inyandiko z’Abanyeshuri', staff_documents: 'Inyandiko z’Abakozi', bylaws: 'Amategeko Ngengamikorere', other: 'Ibindi',
};
fr.documents.types = {
  cooperative_registration_certificate: 'Certificat d’enregistrement de la coopérative', certificates: 'Certificats', cooperative_bylaws_constitution: 'Statuts / Constitution de la coopérative', policies: 'Politiques', general_assembly_minutes: 'Procès-verbal de l’Assemblée générale', board_meeting_minutes: 'Procès-verbal du Conseil', management_meeting_minutes: 'Procès-verbal de la direction', meeting_agenda: 'Ordre du jour', annual_general_meeting_documents: 'Documents de l’Assemblée générale annuelle', member_register: 'Registre des membres', membership_documents: 'Documents d’adhésion', financial_reports: 'Rapports financiers', audit_reports: 'Rapports d’audit', annual_reports: 'Rapports annuels', strategic_plan: 'Plan stratégique', business_plan: 'Plan d’affaires', production_reports: 'Rapports de production', contracts_agreements: 'Contrats / Accords', government_correspondence: 'Correspondance gouvernementale', group_registration: 'Enregistrement du groupe', group_constitution: 'Constitution du groupe', group_rules: 'Règles du groupe', meeting_minutes: 'Procès-verbal de réunion', attendance_records: 'Registres de présence', financial_records: 'Dossiers financiers', production_records: 'Dossiers de production', training_documents: 'Documents de formation', agreements: 'Accords', business_registration: 'Enregistrement commercial', business_license: 'Licence commerciale', company_policies: 'Politiques de l’entreprise', board_minutes: 'Procès-verbal du Conseil', financial_statements: 'États financiers', invoices: 'Factures', tax_documents: 'Documents fiscaux', contracts: 'Contrats', compliance_documents: 'Documents de conformité', employee_documents: 'Documents des employés', registration_certificate: 'Certificat d’enregistrement', constitution: 'Constitution', project_documents: 'Documents de projet', monitoring_evaluation_reports: 'Rapports de suivi et évaluation', donor_agreements: 'Accords avec les donateurs', registration_documents: 'Documents d’enregistrement', school_policies: 'Politiques scolaires', academic_reports: 'Rapports académiques', student_records: 'Dossiers des élèves', staff_documents: 'Documents du personnel', bylaws: 'Règlements', other: 'Autre',
};

en.organizationContext = {
  organization: 'Organization', noneSelected: 'No Organization Selected', noCurrentOrganization: 'Current organization: none',
  currentOrganization: 'Current Organization: {{name}}', selectOrganization: 'Select Organization', loading: 'Loading organizations…',
  organizationsLoadError: 'Authorized organizations could not be loaded.', noAuthorizedOrganizations: 'No authorized organizations are available.',
  genericDescription: 'Select an organization to view this information.', dashboardDescription: 'Select an organization to view its dashboard data.',
  dashboardModules: 'Organization context controls farmers, members, groups, production, inventory, finance, documents, and reports.',
  farmersDescription: 'Select an organization to view and manage farmers.', membersDescription: 'Select an organization to view and manage members.',
  groupsDescription: 'Select an organization to view and manage farmer groups.', productionDescription: 'Select an organization to view production records.',
  inventoryDescription: 'Select an organization to view inventory.', financeDescription: 'Select an organization to view finance data.',
  documentsDescription: 'Select an organization to view organization documents.', reportsDescription: 'Select an organization to view reports.',
  staffDescription: 'Select an organization to view and manage its staff accounts.',
};
rw.organizationContext = {
  organization: 'Umuryango', noneSelected: 'Nta Muryango Wahiswemo', noCurrentOrganization: 'Umuryango uri gukorerwamo: nta wo',
  currentOrganization: 'Umuryango Uri Gukorerwamo: {{name}}', selectOrganization: 'Hitamo Umuryango', loading: 'Imiryango irimo gutangizwa…',
  organizationsLoadError: 'Ntibyashobotse kubona imiryango wemerewe.', noAuthorizedOrganizations: 'Nta muryango wemerewe gukoresha uhari.',
  genericDescription: 'Hitamo umuryango kugira ngo ubone aya makuru.', dashboardDescription: 'Hitamo umuryango kugira ngo ubone amakuru y’imbonerahamwe yawo.',
  dashboardModules: 'Umuryango wahiswemo ugena abahinzi, abanyamuryango, amatsinda, umusaruro, ububiko, imari, inyandiko na raporo.',
  farmersDescription: 'Hitamo umuryango kugira ngo urebe kandi ucunge abahinzi.', membersDescription: 'Hitamo umuryango kugira ngo urebe kandi ucunge abanyamuryango.',
  groupsDescription: 'Hitamo umuryango kugira ngo urebe kandi ucunge amatsinda y’abahinzi.', productionDescription: 'Hitamo umuryango kugira ngo urebe inyandiko z’umusaruro.',
  inventoryDescription: 'Hitamo umuryango kugira ngo urebe ububiko.', financeDescription: 'Hitamo umuryango kugira ngo urebe amakuru y’imari.',
  documentsDescription: 'Hitamo umuryango kugira ngo urebe inyandiko zawo.', reportsDescription: 'Hitamo umuryango kugira ngo urebe raporo.',
  staffDescription: 'Hitamo umuryango kugira ngo urebe kandi ucunge konti z’abakozi bawo.',
};
fr.organizationContext = {
  organization: 'Organisation', noneSelected: 'Aucune organisation sélectionnée', noCurrentOrganization: 'Organisation actuelle : aucune',
  currentOrganization: 'Organisation actuelle : {{name}}', selectOrganization: 'Sélectionner une organisation', loading: 'Chargement des organisations…',
  organizationsLoadError: 'Impossible de charger les organisations autorisées.', noAuthorizedOrganizations: 'Aucune organisation autorisée n’est disponible.',
  genericDescription: 'Sélectionnez une organisation pour afficher ces informations.', dashboardDescription: 'Sélectionnez une organisation pour afficher les données de son tableau de bord.',
  dashboardModules: 'Le contexte d’organisation contrôle les agriculteurs, membres, groupes, productions, stocks, finances, documents et rapports.',
  farmersDescription: 'Sélectionnez une organisation pour afficher et gérer ses agriculteurs.', membersDescription: 'Sélectionnez une organisation pour afficher et gérer ses membres.',
  groupsDescription: 'Sélectionnez une organisation pour afficher et gérer ses groupements.', productionDescription: 'Sélectionnez une organisation pour afficher ses productions.',
  inventoryDescription: 'Sélectionnez une organisation pour afficher son inventaire.', financeDescription: 'Sélectionnez une organisation pour afficher ses finances.',
  documentsDescription: 'Sélectionnez une organisation pour afficher ses documents.', reportsDescription: 'Sélectionnez une organisation pour afficher ses rapports.',
  staffDescription: 'Sélectionnez une organisation pour afficher et gérer les comptes de son personnel.',
};

Object.assign(en.team, {
  manageSystemAccess: 'Manage System Access', platformRole: 'Platform role', lastLogin: 'Last login', neverSignedIn: 'Never signed in',
  accountActivationStatus: 'Account activation status', platformAccountsOnly: 'Only independent platform accounts can be linked to the SmartBridge Team.',
});
Object.assign(rw.team, {
  manageSystemAccess: 'Gucunga Uburenganzira bwa Sisitemu', platformRole: 'Uruhare ku rubuga', lastLogin: 'Igihe yaherukaga kwinjira', neverSignedIn: 'Ntarinjira',
  accountActivationStatus: 'Imimerere yo gufungura konti', platformAccountsOnly: 'Konti zigenga z’urubuga ni zo zonyine zishobora guhuzwa n’Itsinda rya SmartBridge.',
});
Object.assign(fr.team, {
  manageSystemAccess: 'Gérer l’accès au système', platformRole: 'Rôle de plateforme', lastLogin: 'Dernière connexion', neverSignedIn: 'Jamais connecté',
  accountActivationStatus: 'Statut d’activation du compte', platformAccountsOnly: 'Seuls les comptes de plateforme indépendants peuvent être liés à l’équipe SmartBridge.',
});

en.organizationStaff = { add: 'Add staff account', loading: 'Loading organization staff…', empty: 'No staff accounts yet.', loadError: 'Could not load organization staff.', subtitle: 'Staff accounts for {{name}}.', organizationRole: 'Organization role' };
rw.organizationStaff = { add: 'Ongeraho konti y’umukozi', loading: 'Konti z’abakozi zirimo gutangizwa…', empty: 'Nta konti z’abakozi zirashyirwaho.', loadError: 'Ntibyashobotse kubona abakozi b’umuryango.', subtitle: 'Konti z’abakozi ba {{name}}.', organizationRole: 'Uruhare mu muryango' };
fr.organizationStaff = { add: 'Ajouter un compte du personnel', loading: 'Chargement du personnel…', empty: 'Aucun compte du personnel.', loadError: 'Impossible de charger le personnel de l’organisation.', subtitle: 'Comptes du personnel de {{name}}.', organizationRole: 'Rôle dans l’organisation' };

const savedLanguage = localStorage.getItem('scfmp_language') || 'en';

i18n.use(initReactI18next).init({
  resources: { en: { translation: en }, rw: { translation: rw }, fr: { translation: fr } },
  lng: ['en', 'rw', 'fr'].includes(savedLanguage) ? savedLanguage : 'en',
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
});

document.documentElement.lang = i18n.language;
i18n.on('languageChanged', (language) => {
  localStorage.setItem('scfmp_language', language);
  document.documentElement.lang = language;
});

export default i18n;
