import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

const fileBase = (report) =>
  `scfmp-${report.metadata.module}-${report.metadata.generated_at.slice(0, 10)}`;

const headerRows = (report) => [
  ['SCFMP — Smart Cooperative & Farmer Management Platform'],
  [report.metadata.title],
  [`Cooperative: ${report.metadata.cooperative}`],
  [`Generated: ${new Date(report.metadata.generated_at).toLocaleString()}`],
  [`Generated by: ${report.metadata.generated_by}`],
  [`Records: ${report.metadata.record_count}`],
  [],
];

export const exportReportToExcel = (report) => {
  const rows = [
    ...headerRows(report),
    report.columns.map((column) => column.label),
    ...report.rows.map((row) => report.columns.map((column) => row[column.key] ?? '')),
  ];
  const worksheet = XLSX.utils.aoa_to_sheet(rows);
  worksheet['!cols'] = report.columns.map((column) => ({
    wch: Math.max(14, column.label.length + 3),
  }));
  worksheet['!freeze'] = { xSplit: 0, ySplit: 8 };
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, report.metadata.title.slice(0, 31));
  workbook.Props = {
    Title: report.metadata.title,
    Author: report.metadata.generated_by,
    Company: 'SCFMP',
    CreatedDate: new Date(report.metadata.generated_at),
  };
  XLSX.writeFile(workbook, `${fileBase(report)}.xlsx`, { compression: true });
};

export const exportReportToPdf = (report) => {
  const landscape = report.columns.length > 7;
  const document = new jsPDF({ orientation: landscape ? 'landscape' : 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = document.internal.pageSize.getWidth();

  document.setFillColor(26, 73, 52);
  document.circle(16, 15, 7, 'F');
  document.setTextColor(255, 255, 255);
  document.setFont('helvetica', 'bold');
  document.setFontSize(9);
  document.text('S', 14.6, 18);
  document.setTextColor(25, 37, 31);
  document.setFontSize(15);
  document.text(report.metadata.title, 27, 13);
  document.setFont('helvetica', 'normal');
  document.setTextColor(95, 105, 100);
  document.setFontSize(8.5);
  document.text(`SCFMP  •  ${report.metadata.cooperative}`, 27, 18);
  document.text(
    `${new Date(report.metadata.generated_at).toLocaleString()}  •  ${report.metadata.generated_by}  •  ${report.metadata.record_count} records`,
    27,
    23
  );

  autoTable(document, {
    startY: 29,
    head: [report.columns.map((column) => column.label)],
    body: report.rows.map((row) => report.columns.map((column) => row[column.key] ?? '')),
    theme: 'grid',
    styles: { fontSize: landscape ? 6.5 : 7.5, cellPadding: 2, overflow: 'linebreak' },
    headStyles: { fillColor: [26, 73, 52], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [246, 244, 237] },
    margin: { left: 10, right: 10, bottom: 13 },
    didDrawPage: () => {
      const page = document.internal.getCurrentPageInfo().pageNumber;
      document.setFontSize(8);
      document.setTextColor(110, 110, 110);
      document.text(`SCFMP • ${report.metadata.title}`, 10, document.internal.pageSize.getHeight() - 6);
      document.text(`Page ${page}`, pageWidth - 10, document.internal.pageSize.getHeight() - 6, { align: 'right' });
    },
  });
  document.save(`${fileBase(report)}.pdf`);
};

const escapeHtml = (value) => String(value ?? '')
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')
  .replaceAll("'", '&#039;');

export const printReport = (report) => {
  const popup = window.open('', '_blank', 'noopener,noreferrer');
  if (!popup) throw new Error('Print window was blocked');
  popup.document.write(`<!doctype html><html lang="${escapeHtml(report.metadata.language)}"><head><title>${escapeHtml(report.metadata.title)}</title>
    <style>
      @page { margin: 16mm 10mm 18mm; }
      body { font-family: Arial, sans-serif; color: #19251f; margin: 0; }
      header { display: flex; gap: 14px; align-items: center; border-bottom: 2px solid #1a4934; padding-bottom: 12px; margin-bottom: 16px; }
      .logo { display: grid; place-items: center; width: 44px; height: 44px; border-radius: 50%; background: #1a4934; color: white; font-weight: 700; font-size: 20px; }
      h1 { font-size: 20px; margin: 0 0 5px; } p { color: #65716b; font-size: 11px; margin: 2px 0; }
      table { border-collapse: collapse; width: 100%; font-size: 9px; }
      th { background: #1a4934; color: white; text-align: left; } th, td { border: 1px solid #d8d3c5; padding: 6px; }
      tr:nth-child(even) td { background: #f6f4ed; }
      footer { position: fixed; bottom: -12mm; left: 0; right: 0; font-size: 9px; color: #65716b; border-top: 1px solid #d8d3c5; padding-top: 5px; }
    </style></head><body><header><div class="logo">S</div><div><h1>${escapeHtml(report.metadata.title)}</h1>
    <p>SCFMP • ${escapeHtml(report.metadata.cooperative)}</p><p>${escapeHtml(new Date(report.metadata.generated_at).toLocaleString())} • ${escapeHtml(report.metadata.generated_by)} • ${report.metadata.record_count} records</p></div></header>
    <table><thead><tr>${report.columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join('')}</tr></thead><tbody>
    ${report.rows.map((row) => `<tr>${report.columns.map((column) => `<td>${escapeHtml(row[column.key])}</td>`).join('')}</tr>`).join('')}
    </tbody></table><footer>SCFMP — ${escapeHtml(report.metadata.title)}</footer></body></html>`);
  popup.document.close();
  popup.focus();
  popup.print();
};
